export type Category =
  | "T6 Ring"
  | "T6 Ability"
  | "T13 Weapon"
  | "T13 Armor"
  | "Potion"
  | "Egg"
  | "Consumable"
  | "UT/ST";

export type CatalogItem = {
  id: string;
  name: string;
  category: Category;
  subtype?: string;
};

export const CATALOG: CatalogItem[] = [
  { id: "ubatk", name: "Ring of Unbound Attack", category: "T6 Ring" },
  { id: "ubdef", name: "Ring of Unbound Defense", category: "T6 Ring" },
  { id: "ubdex", name: "Ring of Unbound Dexterity", category: "T6 Ring" },
  { id: "ubhp", name: "Ring of Unbound Health", category: "T6 Ring" },
  { id: "ubmp", name: "Ring of Unbound Magic", category: "T6 Ring" },
  { id: "ubspd", name: "Ring of Unbound Speed", category: "T6 Ring" },
  { id: "ubvit", name: "Ring of Unbound Vitality", category: "T6 Ring" },
  { id: "ubwis", name: "Ring of Unbound Wisdom", category: "T6 Ring" },
  { id: "rod", name: "Ring of Decades", category: "T6 Ring" },
  { id: "tfr", name: "The Forgotten Ring", category: "T6 Ring" },

  { id: "thg", name: "Tome of Holy Guidance", category: "T6 Ability", subtype: "Tome" },
  { id: "ces", name: "Colossus Shield", category: "T6 Ability", subtype: "Shield" },
  { id: "cgc", name: "Cloak of Ghostly Concealment", category: "T6 Ability", subtype: "Cloak" },
  { id: "qem", name: "Quiver of Elvish Mastery", category: "T6 Ability", subtype: "Quiver" },
  { id: "hgg", name: "Helm of the Great General", category: "T6 Ability", subtype: "Helm" },
  { id: "bsp", name: "Baneserpent Poison", category: "T6 Ability", subtype: "Poison" },
  { id: "bss", name: "Bloodsucker Skull", category: "T6 Ability", subtype: "Skull" },
  { id: "gct", name: "Giantcatcher Trap", category: "T6 Ability", subtype: "Trap" },
  { id: "pfo", name: "Planefetter Orb", category: "T6 Ability", subtype: "Orb" },
  { id: "poa", name: "Prism of Apparitions", category: "T6 Ability", subtype: "Prism" },
  { id: "sos", name: "Scepter of Storms", category: "T6 Ability", subtype: "Scepter" },
  { id: "dmc", name: "Doom Circle", category: "T6 Ability", subtype: "Star" },
  { id: "rwz", name: "Royal Wakizashi", category: "T6 Ability", subtype: "Wakizashi" },
  { id: "skl", name: "Skyward Lute", category: "T6 Ability", subtype: "Lute" },
  { id: "svm", name: "Sovereign Mace", category: "T6 Ability", subtype: "Mace" },
  { id: "gsh", name: "Great Shinobi Sheath", category: "T6 Ability", subtype: "Sheath" },
  { id: "eds", name: "Elemental Detonation Spell", category: "T6 Ability", subtype: "Spell" },
  { id: "sbc", name: "Seal of the Blessed Champion", category: "T6 Ability", subtype: "Seal" },
  { id: "soh", name: "Sigil of the Horse", category: "T6 Ability", subtype: "Sigil" },

  { id: "sos_w", name: "Sword of Splendor", category: "T13 Weapon", subtype: "Sword" },
  { id: "dsd", name: "Dagger of Sinister Deeds", category: "T13 Weapon", subtype: "Dagger" },
  { id: "msb", name: "Moonstone Blades", category: "T13 Weapon", subtype: "Dual Blades" },
  { id: "bme", name: "Bow of Mystical Energy", category: "T13 Weapon", subtype: "Bow" },
  { id: "lms", name: "Longbow of the Morning Spirit", category: "T13 Weapon", subtype: "Longbow" },
  { id: "msc", name: "Morning Star of Conjuration", category: "T13 Weapon", subtype: "Morning Star" },
  { id: "woe", name: "Wand of Evocation", category: "T13 Weapon", subtype: "Wand" },
  { id: "shl", name: "Spellblade of the Heavens Light", category: "T13 Weapon", subtype: "Spellblade" },
  { id: "svu", name: "Staff of the Vital Unity", category: "T13 Weapon", subtype: "Staff" },
  { id: "sst", name: "Sunset Tachi", category: "T13 Weapon", subtype: "Tachi" },
  { id: "sdm", name: "Sadamune", category: "T13 Weapon", subtype: "Katana" },
  { id: "dvf", name: "Divine Flail", category: "T13 Weapon", subtype: "Flail" },

  { id: "wha", name: "Wyrmhide Armor", category: "T13 Armor", subtype: "Heavy" },
  { id: "doma", name: "Dominion Armor", category: "T13 Armor", subtype: "Heavy" },
  { id: "rsm", name: "Robe of the Star Mother", category: "T13 Armor", subtype: "Robe" },

  { id: "patk", name: "Potion of Attack", category: "Potion" },
  { id: "pdef", name: "Potion of Defense", category: "Potion" },
  { id: "pdex", name: "Potion of Dexterity", category: "Potion" },
  { id: "plife", name: "Potion of Life", category: "Potion" },
  { id: "pmana", name: "Potion of Mana", category: "Potion" },
  { id: "pspd", name: "Potion of Speed", category: "Potion" },
  { id: "pvit", name: "Potion of Vitality", category: "Potion" },
  { id: "pwis", name: "Potion of Wisdom", category: "Potion" },
  { id: "gpatk", name: "Greater Potion of Attack", category: "Potion" },
  { id: "gpdef", name: "Greater Potion of Defense", category: "Potion" },
  { id: "gpdex", name: "Greater Potion of Dexterity", category: "Potion" },
  { id: "gplife", name: "Greater Potion of Life", category: "Potion" },
  { id: "gpmana", name: "Greater Potion of Mana", category: "Potion" },
  { id: "gpspd", name: "Greater Potion of Speed", category: "Potion" },
  { id: "gpvit", name: "Greater Potion of Vitality", category: "Potion" },
  { id: "gpwis", name: "Greater Potion of Wisdom", category: "Potion" },

  { id: "uegg_qmark", name: "Uncommon ???? Egg", category: "Egg" },
  { id: "regg_qmark", name: "Rare ???? Egg", category: "Egg" },
  { id: "uegg_aquatic", name: "Uncommon Aquatic Egg", category: "Egg" },
  { id: "regg_aquatic", name: "Rare Aquatic Egg", category: "Egg" },
  { id: "uegg_automaton", name: "Uncommon Automaton Egg", category: "Egg" },
  { id: "regg_automaton", name: "Rare Automaton Egg", category: "Egg" },
  { id: "uegg_avian", name: "Uncommon Avian Egg", category: "Egg" },
  { id: "regg_avian", name: "Rare Avian Egg", category: "Egg" },
  { id: "uegg_canine", name: "Uncommon Canine Egg", category: "Egg" },
  { id: "regg_canine", name: "Rare Canine Egg", category: "Egg" },
  { id: "uegg_exotic", name: "Uncommon Exotic Egg", category: "Egg" },
  { id: "regg_exotic", name: "Rare Exotic Egg", category: "Egg" },
  { id: "uegg_farm", name: "Uncommon Farm Egg", category: "Egg" },
  { id: "regg_farm", name: "Rare Farm Egg", category: "Egg" },
  { id: "uegg_feline", name: "Uncommon Feline Egg", category: "Egg" },
  { id: "regg_feline", name: "Rare Feline Egg", category: "Egg" },
  { id: "uegg_humanoid", name: "Uncommon Humanoid Egg", category: "Egg" },
  { id: "regg_humanoid", name: "Rare Humanoid Egg", category: "Egg" },
  { id: "uegg_insect", name: "Uncommon Insect Egg", category: "Egg" },
  { id: "regg_insect", name: "Rare Insect Egg", category: "Egg" },
  { id: "uegg_mystery", name: "Uncommon Mystery Egg", category: "Egg" },
  { id: "regg_mystery", name: "Rare Mystery Egg", category: "Egg" },
  { id: "uegg_penguin", name: "Uncommon Penguin Egg", category: "Egg" },
  { id: "regg_penguin", name: "Rare Penguin Egg", category: "Egg" },
  { id: "uegg_reptile", name: "Uncommon Reptile Egg", category: "Egg" },
  { id: "regg_reptile", name: "Rare Reptile Egg", category: "Egg" },
  { id: "uegg_spooky", name: "Uncommon Spooky Egg", category: "Egg" },
  { id: "regg_spooky", name: "Rare Spooky Egg", category: "Egg" },
  { id: "uegg_woodland", name: "Uncommon Woodland Egg", category: "Egg" },
  { id: "regg_woodland", name: "Rare Woodland Egg", category: "Egg" },

  { id: "wcinc", name: "Wine Cellar Incantation", category: "Consumable" },

  { id: "sep", name: "Staff of Extreme Prejudice", category: "UT/ST", subtype: "Staff" },
  { id: "fpm", name: "Fitted Protective Matrix", category: "UT/ST", subtype: "Armor" },
  { id: "hpm", name: "Heavy Protective Matrix", category: "UT/ST", subtype: "Armor" },
  { id: "mpm", name: "Magic Protective Matrix", category: "UT/ST", subtype: "Armor" },
  { id: "cca", name: "Candy-Coated Armor", category: "UT/ST", subtype: "Armor" },
  { id: "aod", name: "Amulet of Dispersion", category: "UT/ST", subtype: "Ring" },

  { id: "sunj", name: "Sun's Judgement", category: "UT/ST" },
  { id: "fbld", name: "Fire Blade", category: "UT/ST" },
  { id: "coc", name: "Comet of Calamity", category: "UT/ST" },
  { id: "dued", name: "Dueling Daggers", category: "UT/ST", subtype: "Dagger" },
  { id: "snbw", name: "Snowblind Wand", category: "UT/ST", subtype: "Wand" },
  { id: "fst", name: "Foramite Staff", category: "UT/ST", subtype: "Staff" },
  { id: "acsl", name: "Acidic Slasher", category: "UT/ST" },
  { id: "wlw", name: "Warlord Wand", category: "UT/ST", subtype: "Wand" },
  { id: "gagl", name: "Gaseous Glaive", category: "UT/ST" },
  { id: "blzb", name: "Blazon Bow", category: "UT/ST", subtype: "Bow" },
  { id: "ser", name: "Snake Eye Ring", category: "UT/ST", subtype: "Ring" },
  { id: "dblade", name: "Demon Blade", category: "UT/ST", subtype: "Sword" },
  { id: "dbow", name: "Doom Bow", category: "UT/ST", subtype: "Bow" },
  { id: "ross", name: "Ring of Skeletal Specters", category: "UT/ST", subtype: "Ring" },
  // Hand-added: the wiki flags it soulbound (wrong — it's tradeable in-game), so
  // the scraper skips it. Kept outside the auto-synced block so a re-sync won't drop it.
  { id: "spider_shuriken", name: "Spider Shuriken", category: "UT/ST", subtype: "Star" },



  // --- tradeable (auto-synced from equip.xml) ---
  { id: "scorchium_stone", name: "Scorchium Stone", category: "UT/ST" },
  { id: "seal_of_cubic_conundra", name: "Seal of Cubic Conundra", category: "UT/ST" },
  { id: "kat_tsunami", name: "Tsunami", category: "UT/ST" },
  { id: "kat_arashi", name: "Arashi", category: "UT/ST" },
  { id: "sunken_ring", name: "Sunken Ring", category: "UT/ST", subtype: "Ring" },
  { id: "s_h_e_a_t_h", name: "S.H.E.A.T.H.", category: "UT/ST" },

  // --- untiered tradeable (auto-synced from realm.wiki) ---
  { id: "almandine_ring_of_wrath", name: "Almandine Ring of Wrath", category: "UT/ST", subtype: "Ring" },
  { id: "brewer_s_bangle", name: "Brewer's Bangle", category: "UT/ST", subtype: "Ring" },
  { id: "candy_ring", name: "Candy Ring", category: "UT/ST", subtype: "Ring" },
  { id: "captain_s_ring", name: "Captain's Ring", category: "UT/ST", subtype: "Ring" },
  { id: "chef_s_hat", name: "Chef's Hat", category: "UT/ST", subtype: "Ring" },
  { id: "coral_ring", name: "Coral Ring", category: "UT/ST", subtype: "Ring" },
  { id: "corsair", name: "Corsair Ring", category: "UT/ST", subtype: "Ring" },
  { id: "crystal_bone_ring", name: "Crystal Bone Ring", category: "UT/ST", subtype: "Ring" },
  { id: "crystal_key", name: "Crystal Key", category: "UT/ST", subtype: "Ring" },
  { id: "enchanted_ice_shard", name: "Enchanted Ice Shard", category: "UT/ST", subtype: "Ring" },
  { id: "experimental_ring", name: "Experimental Ring", category: "UT/ST", subtype: "Ring" },
  { id: "fairy_ring", name: "Fairy Ring", category: "UT/ST", subtype: "Ring" },
  { id: "geb_s_ring_of_wisdom", name: "Geb's Ring of Wisdom", category: "UT/ST", subtype: "Ring" },
  { id: "legacy_forgotten_ring", name: "Legacy Forgotten Ring", category: "UT/ST", subtype: "Ring" },
  { id: "legacy_ring_of_pure_wishes", name: "Legacy Ring of Pure Wishes", category: "UT/ST", subtype: "Ring" },
  { id: "legacy_spectral_ring_of_horrors", name: "Legacy Spectral Ring of Horrors", category: "UT/ST", subtype: "Ring" },
  { id: "mask_of_anubis", name: "Mask of Anubis", category: "UT/ST", subtype: "Ring" },
  { id: "mask_of_cnidaria", name: "Mask of Cnidaria", category: "UT/ST", subtype: "Ring" },
  { id: "mask_of_lightning", name: "Mask of Lightning", category: "UT/ST", subtype: "Ring" },
  { id: "mask_of_mucus", name: "Mask of Mucus", category: "UT/ST", subtype: "Ring" },
  { id: "oryxmas_ornament_energized", name: "Oryxmas Ornament Energized", category: "UT/ST", subtype: "Ring" },
  { id: "oryxmas_ornament_exposed", name: "Oryxmas Ornament Exposed", category: "UT/ST", subtype: "Ring" },
  { id: "oryxmas_ornament_weak", name: "Oryxmas Ornament Weak", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_divine_faith", name: "Ring of Divine Faith", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_the_burning_sun", name: "Ring of the Burning Sun", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_the_covetous_heart", name: "Ring of the Covetous Heart", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_the_nile", name: "Ring of the Nile", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_the_pyramid", name: "Ring of the Pyramid", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_the_sphinx", name: "Ring of the Sphinx", category: "UT/ST", subtype: "Ring" },
  { id: "spider_s_eye_ring", name: "Spider's Eye Ring", category: "UT/ST", subtype: "Ring" },
  { id: "superior_mask_of_anubis", name: "Superior Mask of Anubis", category: "UT/ST", subtype: "Ring" },
  { id: "superior_mask_of_cnidaria", name: "Superior Mask of Cnidaria", category: "UT/ST", subtype: "Ring" },
  { id: "superior_mask_of_lightning", name: "Superior Mask of Lightning", category: "UT/ST", subtype: "Ring" },
  { id: "superior_mask_of_mucus", name: "Superior Mask of Mucus", category: "UT/ST", subtype: "Ring" },
  { id: "leather_cheater", name: "Cheater Light Armor", category: "UT/ST", subtype: "Armor" },
  { id: "leather_chef", name: "Chefs Atire", category: "UT/ST", subtype: "Armor" },
  { id: "leather_chocolate", name: "Chocolate Armor", category: "UT/ST", subtype: "Armor" },
  { id: "leather_coralsilk", name: "Coral Silk Armor", category: "UT/ST", subtype: "Armor" },
  { id: "leather_construction", name: "Fitted Construction Vest", category: "UT/ST", subtype: "Armor" },
  { id: "frost_drakehide", name: "Frost Drake Hide Armor", category: "UT/ST", subtype: "Armor" },
  { id: "leather_greaterhosen", name: "Greaterhosen", category: "UT/ST", subtype: "Armor" },
  { id: "leather_harlequin", name: "Harlequin Armor", category: "UT/ST", subtype: "Armor" },
  { id: "leather_skuld", name: "Legacy Mantle of Skuld", category: "UT/ST", subtype: "Armor" },
  { id: "leather_shadowbeast", name: "Shadowbeast Hide", category: "UT/ST", subtype: "Armor" },
  { id: "leather_snakeskin", name: "Snakeskin Armor", category: "UT/ST", subtype: "Armor" },
  { id: "leather_spectral", name: "Spectral Cloth Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_almandine", name: "Almandine Armor of Anger", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_heavenly", name: "Armor of Heavenly Light", category: "UT/ST", subtype: "Armor" },
  { id: "bbp", name: "Berserker's Breastplate", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_cask", name: "Cask Corslet", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_cheater", name: "Cheater Heavy Armor", category: "UT/ST", subtype: "Armor" },
  { id: "frost_citadel", name: "Frost Citadel Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_construction", name: "Heavy Construction Vest", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_fairyplate", name: "Legacy Fairy Plate", category: "UT/ST", subtype: "Armor" },
  { id: "lovebite_armor", name: "Lovebite Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_resurrected", name: "Resurrected Warrior's Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_warped", name: "Warped Mantle", category: "UT/ST", subtype: "Armor" },
  { id: "chasuble_of_holy_light", name: "Chasuble of Holy Light", category: "UT/ST", subtype: "Armor" },
  { id: "cheater_robe", name: "Cheater Robe", category: "UT/ST", subtype: "Armor" },
  { id: "frost_elemrobe", name: "Frost Elementalist Robe", category: "UT/ST", subtype: "Armor" },
  { id: "legacy_robe_of_twilight", name: "Legacy Robe of Twilight", category: "UT/ST", subtype: "Armor" },
  { id: "magic_construction_vest", name: "Magic Construction Vest", category: "UT/ST", subtype: "Armor" },
  { id: "robe_of_dark_summoning", name: "Robe of Dark Summoning", category: "UT/ST", subtype: "Armor" },
  { id: "robe_of_the_mad_scientist", name: "Robe of the Mad Scientist", category: "UT/ST", subtype: "Armor" },
  { id: "robe_of_the_summer_solstice", name: "Robe of the Summer Solstice", category: "UT/ST", subtype: "Armor" },
  { id: "robe_of_the_tlatoani", name: "Robe of the Tlatoani", category: "UT/ST", subtype: "Armor" },
  { id: "shendyt_of_geb", name: "Shendyt of Geb", category: "UT/ST", subtype: "Armor" },
  { id: "soulless_robe", name: "Soulless Robe", category: "UT/ST", subtype: "Armor" },
  { id: "tlatoani_s_shroud", name: "Tlatoani's Shroud", category: "UT/ST", subtype: "Armor" },
  { id: "woodland_robe", name: "Woodland Robe", category: "UT/ST", subtype: "Armor" },
  { id: "book_of_geb", name: "Book of Geb", category: "UT/ST" },
  { id: "botany_book", name: "Botany Book", category: "UT/ST" },
  { id: "nativity_tome", name: "Nativity Tome", category: "UT/ST" },
  { id: "necronomicon", name: "Necronomicon", category: "UT/ST" },
  { id: "tome_of_holy_protection", name: "Tome of Holy Protection", category: "UT/ST" },
  { id: "tome_of_moral_support", name: "Tome of Moral Support", category: "UT/ST" },
  { id: "tome_of_purification", name: "Tome of Purification", category: "UT/ST" },
  { id: "onyx_shield_of_the_mad_god", name: "Onyx Shield of the Mad God", category: "UT/ST" },
  { id: "resounding_shield", name: "Resounding Shield", category: "UT/ST" },
  { id: "shield_of_pogmur", name: "Shield of Pogmur", category: "UT/ST" },
  { id: "snakeskin_shield", name: "Snakeskin Shield", category: "UT/ST" },
  { id: "tester_wooden_shield", name: "Tester Wooden Shield", category: "UT/ST" },
  { id: "legacy_ancient_spell_pierce", name: "Legacy Ancient Spell: Pierce", category: "UT/ST" },
  { id: "random_spell_extraction_device", name: "Random Spell Extraction Device", category: "UT/ST" },
  { id: "spelling_spell", name: "Spelling Spell", category: "UT/ST" },
  { id: "thousand_suns_spell", name: "Thousand Suns Spell", category: "UT/ST" },
  { id: "vigil_spell", name: "Vigil Spell", category: "UT/ST" },
  { id: "advent_seal", name: "Advent Seal", category: "UT/ST" },
  { id: "legacy_seal_of_the_enchanted_forest", name: "Legacy Seal of the Enchanted Forest", category: "UT/ST" },
  { id: "sandstone_seal", name: "Sandstone Seal", category: "UT/ST" },
  { id: "scholar_s_seal", name: "Scholar's Seal", category: "UT/ST" },
  { id: "seal_of_eternal_life", name: "Seal of Eternal Life", category: "UT/ST" },
  { id: "cloak_planewalker", name: "Cloak of the Planewalker", category: "UT/ST" },
  { id: "cloak_winter", name: "Cloak of Winter", category: "UT/ST" },
  { id: "cloak_eggshell", name: "Eggshell Cowl", category: "UT/ST" },
  { id: "cloak_ghastly", name: "Legacy Ghastly Drape", category: "UT/ST" },
  { id: "cloak_mirror", name: "Mirror Cloak", category: "UT/ST" },
  { id: "archerang", name: "Archerang", category: "UT/ST" },
  { id: "coalbearing_quiver", name: "Coalbearing Quiver", category: "UT/ST" },
  { id: "cocoon_quiver", name: "Cocoon Quiver", category: "UT/ST" },
  { id: "tester_magic_quiver", name: "Tester Magic Quiver", category: "UT/ST" },
  { id: "helm_amber", name: "Amber Encrusted Helmet", category: "UT/ST" },
  { id: "helm_challenger", name: "Challenger Helm", category: "UT/ST" },
  { id: "helm_pathfinder", name: "Pathfinder's Helm", category: "UT/ST" },
  { id: "cursed_canopic_jar", name: "Cursed Canopic Jar", category: "UT/ST" },
  { id: "holly_poison", name: "Holly Poison", category: "UT/ST" },
  { id: "lightning_in_a_bottle", name: "Lightning in a Bottle", category: "UT/ST" },
  { id: "mighty_stein", name: "Mighty Stein", category: "UT/ST" },
  { id: "murky_toxin", name: "Murky Toxin", category: "UT/ST" },
  { id: "plague_poison", name: "Plague Poison", category: "UT/ST" },
  { id: "cracked_crystal_skull", name: "Cracked Crystal Skull", category: "UT/ST" },
  { id: "epiphany_skull", name: "Epiphany Skull", category: "UT/ST" },
  { id: "sealed_crystal_skull", name: "Sealed Crystal Skull", category: "UT/ST" },
  { id: "skull_of_krampus", name: "Skull of Krampus", category: "UT/ST" },
  { id: "greedsnatcher_trap", name: "Greedsnatcher Trap", category: "UT/ST" },
  { id: "helium_trap", name: "Helium Trap", category: "UT/ST" },
  { id: "mimicry_trap", name: "Mimicry Trap", category: "UT/ST" },
  { id: "painbow", name: "Painbow", category: "UT/ST" },
  { id: "enchantment_orb", name: "Enchantment Orb", category: "UT/ST" },
  { id: "karma_orb", name: "Karma Orb", category: "UT/ST" },
  { id: "orb_of_sweet_demise", name: "Orb of Sweet Demise", category: "UT/ST" },
  { id: "snowbound_orb", name: "Snowbound Orb", category: "UT/ST" },
  { id: "soul_of_the_bearer", name: "Soul of the Bearer", category: "UT/ST" },
  { id: "sphere_of_ice", name: "Sphere of Ice", category: "UT/ST" },
  { id: "titan_s_heart_2", name: "Titan's Heart", category: "UT/ST" },
  { id: "fool_s_prism", name: "Fool's Prism", category: "UT/ST" },
  { id: "ghostly_prism", name: "Ghostly Prism", category: "UT/ST" },
  { id: "heart_of_gold_prism", name: "Heart of Gold Prism", category: "UT/ST" },
  { id: "ornamental_prism", name: "Ornamental Prism", category: "UT/ST" },
  { id: "prism_of_dancing_swords", name: "Prism of Dancing Swords", category: "UT/ST" },
  { id: "prismimic", name: "Prismimic", category: "UT/ST" },
  { id: "honey_scepter", name: "Honey Scepter", category: "UT/ST" },
  { id: "honey_scepter_supreme", name: "Honey Scepter Supreme", category: "UT/ST" },
  { id: "scepter_of_fulmination", name: "Scepter of Fulmination", category: "UT/ST" },
  { id: "scepter_of_sainthood", name: "Scepter of Sainthood", category: "UT/ST" },
  { id: "clover_star", name: "Clover Star", category: "UT/ST" },
  { id: "ilex_star", name: "Ilex Star", category: "UT/ST" },
  { id: "testiken", name: "Testiken", category: "UT/ST" },
  { id: "testiken_att", name: "Testiken ATT", category: "UT/ST" },
  { id: "testiken_def", name: "Testiken DEF", category: "UT/ST" },
  { id: "testiken_dex", name: "Testiken DEX", category: "UT/ST" },
  { id: "testiken_spd", name: "Testiken SPD", category: "UT/ST" },
  { id: "testiken_vit", name: "Testiken VIT", category: "UT/ST" },
  { id: "testiken_wis", name: "Testiken WIS", category: "UT/ST" },
  { id: "unshuriken", name: "Unshuriken", category: "UT/ST" },
  { id: "nsfwakizashi", name: "NSFWakizashi", category: "UT/ST" },
  { id: "peppermint_wakizashi", name: "Peppermint Wakizashi", category: "UT/ST" },
  { id: "ronin_s_wakizashi", name: "Ronin's Wakizashi", category: "UT/ST" },
  { id: "wakizashi_of_crossing_fires", name: "Wakizashi of Crossing Fires", category: "UT/ST" },
  { id: "wakizashi_of_eastern_winds", name: "Wakizashi of Eastern Winds", category: "UT/ST" },
  { id: "lullaby", name: "Lullaby", category: "UT/ST" },
  { id: "oryxmas_carol", name: "Oryxmas Carol", category: "UT/ST" },
  { id: "pharaoh_s_requiem", name: "Pharaoh's Requiem", category: "UT/ST" },
  { id: "snake_charmer_pungi", name: "Snake Charmer Pungi", category: "UT/ST" },
  { id: "mace_of_the_celestial_forest", name: "Mace of the Celestial Forest", category: "UT/ST" },
  { id: "mace_of_the_north_pole", name: "Mace of the North Pole", category: "UT/ST" },
  { id: "recursion_mace", name: "Recursion Mace", category: "UT/ST" },
  { id: "an_ancient_s_embrace", name: "An Ancient's Embrace", category: "UT/ST" },
  { id: "quartermaster_scabbard", name: "Quartermaster Scabbard", category: "UT/ST" },
  { id: "snowman_s_sheath", name: "Snowman's Sheath", category: "UT/ST" },
  { id: "volcanic_sheath", name: "Volcanic Sheath", category: "UT/ST" },
  { id: "draconic_insignia", name: "Draconic Insignia", category: "UT/ST" },
  { id: "ao_hsig", name: "Hawkmaster Sigil", category: "UT/ST" },
  { id: "sharktooth_sigil", name: "Sharktooth Sigil", category: "UT/ST" },
  { id: "sigil_of_the_reindeer", name: "Sigil of the Reindeer", category: "UT/ST" },
  { id: "sigil_of_the_rubber_duck", name: "Sigil of the Rubber Duck", category: "UT/ST" },
  { id: "silken_sigil", name: "Silken Sigil", category: "UT/ST" },
  { id: "ancient_stone_sword", name: "Ancient Stone Sword", category: "UT/ST" },
  { id: "apocalypse_feather", name: "Apocalypse Feather", category: "UT/ST" },
  { id: "arap", name: "Arcane Rapier", category: "UT/ST" },
  { id: "crystalsword", name: "Crystal Sword", category: "UT/ST" },
  { id: "doctor_swordsworth", name: "Doctor Swordsworth", category: "UT/ST" },
  { id: "qbc_eggbasher", name: "Egg Basher", category: "UT/ST" },
  { id: "enchiceblade", name: "Enchanted Ice Blade", category: "UT/ST" },
  { id: "ffabulous_fflail", name: "FFabulous FFlail", category: "UT/ST" },
  { id: "frostbite", name: "Frostbite", category: "UT/ST" },
  { id: "hammer_sword", name: "Hammer Sword", category: "UT/ST" },
  { id: "keychain_cutlass", name: "Keychain Cutlass", category: "UT/ST" },
  { id: "flail_lament", name: "Lament of the Frozen Prisoner", category: "UT/ST" },
  { id: "legacy_pixie_enchanted_sword", name: "Legacy Pixie-Enchanted Sword", category: "UT/ST" },
  { id: "flail_yoyo", name: "Lovestruck Yoyo", category: "UT/ST" },
  { id: "mmace_mmurderer", name: "MMace MMurderer", category: "UT/ST" },
  { id: "pkcutlass", name: "Pirate King's Cutlass", category: "UT/ST" },
  { id: "frost_saintnic", name: "Saint Nicolas' Blade", category: "UT/ST" },
  { id: "flail_seismic", name: "Seismic Flail", category: "UT/ST" },
  { id: "silex_s_hammer", name: "Silex's Hammer", category: "UT/ST" },
  { id: "skull_splitter_sword", name: "Skull-splitter Sword", category: "UT/ST" },
  { id: "spectral_sword", name: "Spectral Sword", category: "UT/ST" },
  { id: "swordillum", name: "Sword of Illumination", category: "UT/ST" },
  { id: "sword_of_the_mad_god", name: "Sword of the Mad God", category: "UT/ST" },
  { id: "sword_of_the_rainbow_s_end", name: "Sword of the Rainbow's End", category: "UT/ST" },
  { id: "sword_of_the_unending_chaos", name: "Sword of the Unending Chaos", category: "UT/ST" },
  { id: "the_crimson_blade", name: "The Crimson Blade", category: "UT/ST" },
  { id: "unstable_anomaly", name: "Unstable Anomaly", category: "UT/ST" },
  { id: "vinesword", name: "Vinesword", category: "UT/ST" },
  { id: "flail_void", name: "Void Flail", category: "UT/ST" },
  { id: "dag_icicle", name: "An Icicle", category: "UT/ST" },
  { id: "dag_dirk", name: "Blood Coated Dirk", category: "UT/ST" },
  { id: "bdag", name: "Bone Dagger", category: "UT/ST" },
  { id: "duel_boomerang", name: "Boomerang Blades", category: "UT/ST" },
  { id: "dag_chicken", name: "Chicken Leg of Doom", category: "UT/ST" },
  { id: "dag_corruption", name: "Corruption Cutter", category: "UT/ST" },
  { id: "dag_chaos", name: "Dagger of Eternal Chaos", category: "UT/ST" },
  { id: "dag_amethyst", name: "Dagger of the Amethyst Prism", category: "UT/ST" },
  { id: "dag_rabbit", name: "Dagger of the Hasteful Rabbit", category: "UT/ST" },
  { id: "dag_talon", name: "Dagger of the Terrible Talon", category: "UT/ST" },
  { id: "dag_frostlich", name: "Frost Lich's Finger", category: "UT/ST" },
  { id: "duel_frostbite", name: "Frostbite Blades", category: "UT/ST" },
  { id: "dag_groovymango", name: "Groovy Mango", category: "UT/ST" },
  { id: "duel_hatchling", name: "Hatchling Blades", category: "UT/ST" },
  { id: "duel_heartjewel", name: "Heart Jewel Blades", category: "UT/ST" },
  { id: "dag_heartfind", name: "Heartfind Dagger", category: "UT/ST" },
  { id: "dag_etherite", name: "Legacy Etherite Dagger", category: "UT/ST" },
  { id: "dag_marionette", name: "Marionette Ravager", category: "UT/ST" },
  { id: "dag_mistermango", name: "Mister Mango", category: "UT/ST" },
  { id: "dag_spoon", name: "Needlessly Large Spoon", category: "UT/ST" },
  { id: "dag_poisonfang", name: "Poison Fang Dagger", category: "UT/ST" },
  { id: "dag_prismatic", name: "Prismatic Slasher", category: "UT/ST" },
  { id: "dag_spatula", name: "Spatula Dagger", category: "UT/ST" },
  { id: "dag_spirit", name: "Spirit Dagger", category: "UT/ST" },
  { id: "dag_sunshine", name: "Sunshine Shiv", category: "UT/ST" },
  { id: "dag_toyknife", name: "Toy Knife", category: "UT/ST" },
  { id: "duel_void", name: "Void Blades", category: "UT/ST" },
  { id: "longbow_anteros", name: "Anteros Longbow", category: "UT/ST" },
  { id: "bow_arctic", name: "Arctic Bow", category: "UT/ST" },
  { id: "bow_baked", name: "Baked Bow", category: "UT/ST" },
  { id: "bow_efrost", name: "Bow of Eternal Frost", category: "UT/ST" },
  { id: "bow_nightmares", name: "Bow of Nightmares", category: "UT/ST" },
  { id: "bow_mstar", name: "Bow of the Morning Star", category: "UT/ST" },
  { id: "bow_skyglory", name: "Bow of the Sky's Glory", category: "UT/ST" },
  { id: "bow_bramble", name: "Bramble Bow", category: "UT/ST" },
  { id: "bow_butter", name: "Butter Bow", category: "UT/ST" },
  { id: "bow_clover", name: "Clover Bow", category: "UT/ST" },
  { id: "bow_coral", name: "Coral Bow", category: "UT/ST" },
  { id: "bow_cupid", name: "Cupid's Bow", category: "UT/ST" },
  { id: "longbow_harpoon", name: "Harpoon Longbow", category: "UT/ST" },
  { id: "bow_icicle", name: "Icicle Launcher", category: "UT/ST" },
  { id: "frost_glacierbow", name: "Longbow of the Great Glacier", category: "UT/ST" },
  { id: "longbow_void", name: "Longbow of the Void", category: "UT/ST" },
  { id: "bow_nailgun", name: "Nail Gun Bow", category: "UT/ST" },
  { id: "bow_stringstick", name: "Precisely Calibrated Stringstick", category: "UT/ST" },
  { id: "bow_robobow", name: "Robobow", category: "UT/ST" },
  { id: "qbc_shardlauncher", name: "Shard Launcher", category: "UT/ST" },
  { id: "acidic_aspergillum", name: "Acidic Aspergillum", category: "UT/ST" },
  { id: "caduceus_of_current_craziness", name: "Caduceus of Current Craziness", category: "UT/ST" },
  { id: "caduceus_of_enlightened_chaos", name: "Caduceus Of Enlightened Chaos", category: "UT/ST" },
  { id: "ceremonial_wand", name: "Ceremonial Wand", category: "UT/ST" },
  { id: "qbc_ovipositor", name: "Chocolate Ovipositor", category: "UT/ST" },
  { id: "cwand", name: "Conducting Wand", category: "UT/ST" },
  { id: "crystal_wand", name: "Crystal Wand", category: "UT/ST" },
  { id: "eggcond", name: "Eggstatic Conductor", category: "UT/ST" },
  { id: "eternal_snowflake_wand", name: "Eternal Snowflake Wand", category: "UT/ST" },
  { id: "frozen_wand", name: "Frozen Wand", category: "UT/ST" },
  { id: "lethargic_sentience", name: "Lethargic Sentience", category: "UT/ST" },
  { id: "measuring_wand", name: "Measuring Wand", category: "UT/ST" },
  { id: "morning_star_of_sweet_miracles", name: "Morning Star Of Sweet Miracles", category: "UT/ST" },
  { id: "morning_star_of_the_void", name: "Morning Star of the Void", category: "UT/ST" },
  { id: "present_dispensing_wand", name: "Present Dispensing Wand", category: "UT/ST" },
  { id: "rainbow_rod", name: "Rainbow Rod", category: "UT/ST" },
  { id: "scarlet_etched_branch", name: "Scarlet Etched Branch", category: "UT/ST" },
  { id: "soul_s_guidance", name: "Soul's Guidance", category: "UT/ST" },
  { id: "spicy_wand_of_spice", name: "Spicy Wand of Spice", category: "UT/ST" },
  { id: "sprite_wand", name: "Sprite Wand", category: "UT/ST" },
  { id: "st_abraham_s_wand", name: "St. Abraham's Wand", category: "UT/ST" },
  { id: "frost_northstar", name: "The North Star", category: "UT/ST" },
  { id: "wand_of_ancient_terror", name: "Wand of Ancient Terror", category: "UT/ST" },
  { id: "wand_of_budding_romance", name: "Wand of Budding Romance", category: "UT/ST" },
  { id: "wand_of_egg_cellence", name: "Wand of Egg-cellence", category: "UT/ST" },
  { id: "wand_of_geb", name: "Wand of Geb", category: "UT/ST" },
  { id: "wand_hidden", name: "Wand of Hidden Knowledge", category: "UT/ST" },
  { id: "wand_of_the_bulwark", name: "Wand of the Bulwark", category: "UT/ST" },
  { id: "wand_of_the_summoned_one", name: "Wand of the Summoned One", category: "UT/ST" },
  { id: "frost_winterwand", name: "Winter's Breath Wand", category: "UT/ST" },
  { id: "anatis_staff", name: "Anatis Staff", category: "UT/ST" },
  { id: "barely_attuned_magic_thingy", name: "Barely Attuned Magic Thingy", category: "UT/ST" },
  { id: "qbc_spellblade", name: "Caramel Spellblade", category: "UT/ST" },
  { id: "elder_heartwood_staff", name: "Elder Heartwood Staff", category: "UT/ST" },
  { id: "frost_walkingstick", name: "Frosty's Walking Stick", category: "UT/ST" },
  { id: "hovering_spellblade", name: "Hovering Spellblade", category: "UT/ST" },
  { id: "k_i_d_d_force", name: "K.I.D.D. Force", category: "UT/ST" },
  { id: "k_i_d_d_force_2_0", name: "K.I.D.D. Force 2.0", category: "UT/ST" },
  { id: "koalapow", name: "KoalaPOW", category: "UT/ST" },
  { id: "legacy_sentient_staff", name: "Legacy Sentient Staff", category: "UT/ST" },
  { id: "love_heart_spellblade", name: "Love Heart Spellblade", category: "UT/ST" },
  { id: "screwdriver_staff", name: "Screwdriver Staff", category: "UT/ST" },
  { id: "frost_snowblindsb", name: "Snowblind Spellblade", category: "UT/ST" },
  { id: "spellblade_of_the_void", name: "Spellblade of the Void", category: "UT/ST" },
  { id: "spirit_staff", name: "Spirit Staff", category: "UT/ST" },
  { id: "staff_of_adoration", name: "Staff of Adoration", category: "UT/ST" },
  { id: "staff_of_horrific_knowledge", name: "Staff of Horrific Knowledge", category: "UT/ST" },
  { id: "staff_iceblast", name: "Staff of Iceblast", category: "UT/ST" },
  { id: "staff_of_silver_wings", name: "Staff of Silver Wings", category: "UT/ST" },
  { id: "staff_of_the_crystal_serpent", name: "Staff of the Crystal Serpent", category: "UT/ST" },
  { id: "staff_of_the_rising_sun", name: "Staff of the Rising Sun", category: "UT/ST" },
  { id: "staff_of_the_saint", name: "Staff of the Saint", category: "UT/ST" },
  { id: "staff_of_yuletide_carols", name: "Staff of Yuletide Carols", category: "UT/ST" },
  { id: "the_phylactery", name: "The Phylactery", category: "UT/ST" },
  { id: "kat_arbiter", name: "Arbiter's Wrath", category: "UT/ST" },
  { id: "frost_auroratachi", name: "Aurora Tachi", category: "UT/ST" },
  { id: "kat_ages", name: "Blade of Ages", category: "UT/ST" },
  { id: "kat_blooming", name: "Blade of Blooming", category: "UT/ST" },
  { id: "kat_corrupted", name: "Corrupted Cleaver", category: "UT/ST" },
  { id: "kat_diamond", name: "Diamond-Bladed Katana", category: "UT/ST" },
  { id: "dokunoken", name: "Doku No Ken", category: "UT/ST" },
  { id: "kat_goodfortune", name: "Katana of Good Fortune", category: "UT/ST" },
  { id: "kat_krathana", name: "Krathana", category: "UT/ST" },
  { id: "kat_salju", name: "Salju", category: "UT/ST" },
  { id: "kat_sawblade", name: "Sawblade Katana", category: "UT/ST" },
  { id: "kat_skybound", name: "Skybound Blade", category: "UT/ST" },
  { id: "sweetheart_taichi", name: "Sweetheart Taichi", category: "UT/ST" },
  { id: "kat_useless", name: "Useless Katana", category: "UT/ST" },
  { id: "kat_voidblade", name: "Void Blade", category: "UT/ST" },
  { id: "void_tachi", name: "Void Tachi", category: "UT/ST" },
  { id: "frost_yuki", name: "Yuki", category: "UT/ST" },
  { id: "amulet_of_elemental_air", name: "Amulet of Elemental Air", category: "UT/ST", subtype: "Ring" },
  { id: "amulet_of_elemental_earth", name: "Amulet of Elemental Earth", category: "UT/ST", subtype: "Ring" },
  { id: "amulet_of_elemental_fire", name: "Amulet of Elemental Fire", category: "UT/ST", subtype: "Ring" },
  { id: "amulet_of_elemental_water", name: "Amulet of Elemental Water", category: "UT/ST", subtype: "Ring" },
  { id: "amulet_of_the_great_shaman", name: "Amulet of the Great Shaman", category: "UT/ST", subtype: "Ring" },
  { id: "autarch_amulet", name: "Autarch Amulet", category: "UT/ST", subtype: "Ring" },
  { id: "e_y_e", name: "E.Y.E.", category: "UT/ST", subtype: "Ring" },
  { id: "emblem_of_the_empire", name: "Emblem of the Empire", category: "UT/ST", subtype: "Ring" },
  { id: "hi_scarab", name: "Faded Heart Scarab", category: "UT/ST", subtype: "Ring" },
  { id: "hi_hannya", name: "Fractured Hannya", category: "UT/ST", subtype: "Ring" },
  { id: "frimarra", name: "Frimarra", category: "UT/ST", subtype: "Ring" },
  { id: "geb_s_lost_hedjet", name: "Geb's Lost Hedjet", category: "UT/ST", subtype: "Ring" },
  { id: "mayhem_medallion", name: "Mayhem Medallion", category: "UT/ST", subtype: "Ring" },
  { id: "regal_ring", name: "Regal Ring", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_the_northern_light", name: "Ring of the Northern Light", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_unbound_love", name: "Ring of Unbound Love", category: "UT/ST", subtype: "Ring" },
  { id: "ring_of_wrath", name: "Ring of Wrath", category: "UT/ST", subtype: "Ring" },
  { id: "rose_brooch", name: "Rose Brooch", category: "UT/ST", subtype: "Ring" },
  { id: "hi_opal", name: "Sunken Fire Opal Ring", category: "UT/ST", subtype: "Ring" },
  { id: "sweetener_ring", name: "Sweetener Ring", category: "UT/ST", subtype: "Ring" },
  { id: "thistleleaf_necklace", name: "Thistleleaf Necklace", category: "UT/ST", subtype: "Ring" },
  { id: "tiara_of_eggscellent_sturdiness", name: "Tiara of Eggscellent Sturdiness", category: "UT/ST", subtype: "Ring" },
  { id: "leather_cupid", name: "Cupid's Garments", category: "UT/ST", subtype: "Armor" },
  { id: "leather_leafdragon", name: "Leaf Dragon Hide Armor", category: "UT/ST", subtype: "Armor" },
  { id: "hi_lightsynd", name: "Light Syndicate Attire", category: "UT/ST", subtype: "Armor" },
  { id: "leather_luxurious", name: "Luxurious Leather", category: "UT/ST", subtype: "Armor" },
  { id: "leather_piratequeen", name: "Pirate Queen's Brigandine", category: "UT/ST", subtype: "Armor" },
  { id: "leather_apron", name: "Splatter-proof Apron", category: "UT/ST", subtype: "Armor" },
  { id: "ao_ssh", name: "Squadron Sheathing", category: "UT/ST", subtype: "Armor" },
  { id: "ao_aeg", name: "Aegis Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_cuirass", name: "Cuirass of the Black Blade", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_eggre", name: "Eggre Battle Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_firedragon", name: "Fire Dragon Battle Armor", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_syndicate", name: "Heavy Syndicate Attire", category: "UT/ST", subtype: "Armor" },
  { id: "heavy_apron", name: "Reinforced Apron", category: "UT/ST", subtype: "Armor" },
  { id: "apron_of_conjuring", name: "Apron of Conjuring", category: "UT/ST", subtype: "Armor" },
  { id: "floral_corset", name: "Floral Corset", category: "UT/ST", subtype: "Armor" },
  { id: "ao_jrobe", name: "Judge's Robe", category: "UT/ST", subtype: "Armor" },
  { id: "hi_mysticsynd", name: "Mystic Syndicate Attire", category: "UT/ST", subtype: "Armor" },
  { id: "wanderer_s_cape", name: "Wanderer's Cape", category: "UT/ST", subtype: "Armor" },
  { id: "lod_waterrobe", name: "Water Dragon Silk Robe", category: "UT/ST", subtype: "Armor" },
  { id: "tome_of_frigid_protection", name: "Tome of Frigid Protection", category: "UT/ST" },
  { id: "tome_of_holy_furor", name: "Tome of Holy Furor", category: "UT/ST" },
  { id: "tome_of_pain", name: "Tome of Pain", category: "UT/ST" },
  { id: "tome_of_the_dragon", name: "Tome of the Dragon", category: "UT/ST" },
  { id: "ao_ttg", name: "Tome of the Tarnished Gods", category: "UT/ST" },
  { id: "ao_bbuck", name: "Brutal Buckler", category: "UT/ST" },
  { id: "dragon_slayer", name: "Dragon Slayer", category: "UT/ST" },
  { id: "esoteric_buckler", name: "Esoteric Buckler", category: "UT/ST" },
  { id: "shield_of_flowing_clarity", name: "Shield of Flowing Clarity", category: "UT/ST" },
  { id: "spiteful_scutum", name: "Spiteful Scutum", category: "UT/ST" },
  { id: "spriteful_shield", name: "Spriteful Shield", category: "UT/ST" },
  { id: "cobra_serpentis_scroll", name: "Cobra Serpentis Scroll", category: "UT/ST" },
  { id: "ao_css", name: "Cursed Spire Spell", category: "UT/ST" },
  { id: "jade_storm", name: "Jade Storm", category: "UT/ST" },
  { id: "penetrating_blast_spell", name: "Penetrating Blast Spell", category: "UT/ST" },
  { id: "recurring_terror_spell", name: "Recurring Terror Spell", category: "UT/ST" },
  { id: "vitamine_buster", name: "Vitamine Buster", category: "UT/ST" },
  { id: "wandering_souls_spell", name: "Wandering Souls Spell", category: "UT/ST" },
  { id: "ao_sbg", name: "Seal of the Battle God", category: "UT/ST" },
  { id: "cloak_cubic", name: "Cloak of Cubic Enigma", category: "UT/ST" },
  { id: "ao_cds", name: "Cloak of the Darkened Sun", category: "UT/ST" },
  { id: "cloak_madgod", name: "Cloak of the Mad God", category: "UT/ST" },
  { id: "double_vision_darts", name: "Double Vision Darts", category: "UT/ST" },
  { id: "ao_mjav", name: "Mad Javelin", category: "UT/ST" },
  { id: "q_u_i_v_e_r", name: "Q.U.I.V.E.R.", category: "UT/ST" },
  { id: "quintessential_quiver", name: "Quintessential Quiver", category: "UT/ST" },
  { id: "helm_adamantine", name: "Adamantine Helm", category: "UT/ST" },
  { id: "helm_bubblegum", name: "Bubblegum Bucket", category: "UT/ST" },
  { id: "ao_hem", name: "Helm of Exalted Might", category: "UT/ST" },
  { id: "helm_swiftbunny", name: "Helm of the Swift Bunny", category: "UT/ST" },
  { id: "helm_tipsy", name: "Tipsy Topper", category: "UT/ST" },
  { id: "bottled_lemonade", name: "Bottled Lemonade", category: "UT/ST" },
  { id: "bottled_medusozoan", name: "Bottled Medusozoan", category: "UT/ST" },
  { id: "hi_barrel", name: "Rusted Barrel", category: "UT/ST" },
  { id: "spirit_s_bane", name: "Spirit's Bane", category: "UT/ST" },
  { id: "ao_ttox", name: "Tyrant's Toxin", category: "UT/ST" },
  { id: "ao_dls", name: "Demon Lord's Skull", category: "UT/ST" },
  { id: "ever_green_skull", name: "Ever Green Skull", category: "UT/ST" },
  { id: "maw_of_malignance", name: "Maw of Malignance", category: "UT/ST" },
  { id: "perennial_cranium", name: "Perennial Cranium", category: "UT/ST" },
  { id: "skull_of_endless_torment", name: "Skull of Endless Torment", category: "UT/ST" },
  { id: "ao_bart", name: "Blacklight Artifice", category: "UT/ST" },
  { id: "coral_venom_trap", name: "Coral Venom Trap", category: "UT/ST" },
  { id: "deadly_keg", name: "Deadly Keg", category: "UT/ST" },
  { id: "sulfuric_stone", name: "Sulfuric Stone", category: "UT/ST" },
  { id: "hi_artifact", name: "Forbidden Artifact", category: "UT/ST" },
  { id: "orb_of_aether", name: "Orb of Aether", category: "UT/ST" },
  { id: "ao_ooc", name: "Orb of Conquest", category: "UT/ST" },
  { id: "vision_of_draconis", name: "Vision of Draconis", category: "UT/ST" },
  { id: "prism_of_dire_instability", name: "Prism of Dire Instability", category: "UT/ST" },
  { id: "ao_psl", name: "Prism of Shattered Light", category: "UT/ST" },
  { id: "the_heart_of_the_dragon", name: "The Heart of the Dragon", category: "UT/ST" },
  { id: "cnidaria_rod", name: "Cnidaria Rod", category: "UT/ST" },
  { id: "eggsponential_scepter", name: "Eggsponential Scepter", category: "UT/ST" },
  { id: "scepter_of_devastation", name: "Scepter of Devastation", category: "UT/ST" },
  { id: "scepter_of_the_transgressor", name: "Scepter of the Transgressor", category: "UT/ST" },
  { id: "ao_ssc", name: "Siege Scepter", category: "UT/ST" },
  { id: "hi_stormcaller", name: "Storm Caller", category: "UT/ST" },
  { id: "hanagasaku", name: "Hanagasaku", category: "UT/ST" },
  { id: "igneous_starblossom", name: "Igneous Starblossom", category: "UT/ST" },
  { id: "midnight_star", name: "Midnight Star", category: "UT/ST" },
  { id: "ao_rcl", name: "Rage Claws", category: "UT/ST" },
  { id: "ao_amat", name: "Amaterasu", category: "UT/ST" },
  { id: "sakura_wakizashi", name: "Sakura Wakizashi", category: "UT/ST" },
  { id: "shadow_serpent_sidearm", name: "Shadow Serpent Sidearm", category: "UT/ST" },
  { id: "ao_cwh", name: "Chief's War Horn", category: "UT/ST" },
  { id: "ghost_ship_s_bell", name: "Ghost Ship's Bell", category: "UT/ST" },
  { id: "joker_timbrel", name: "Joker Timbrel", category: "UT/ST" },
  { id: "wavecrest_concertina", name: "Wavecrest Concertina", category: "UT/ST" },
  { id: "crystal_mace", name: "Crystal Mace", category: "UT/ST" },
  { id: "dragon_mace", name: "Dragon Mace", category: "UT/ST" },
  { id: "mace_of_the_depths", name: "Mace of the Depths", category: "UT/ST" },
  { id: "ao_mmace", name: "Mechanical Mace", category: "UT/ST" },
  { id: "ao_blz", name: "Blitz Sheath", category: "UT/ST" },
  { id: "kaiken", name: "Kaiken", category: "UT/ST" },
  { id: "labyrinth_dweller_s_sheath", name: "Labyrinth Dweller's Sheath", category: "UT/ST" },
  { id: "hi_sheath", name: "Sheath of Thunderous Rites", category: "UT/ST" },
  { id: "cheerful_chipper", name: "Cheerful Chipper", category: "UT/ST" },
  { id: "chocsicle", name: "Chocsicle", category: "UT/ST" },
  { id: "def_test_sword", name: "Def Test Sword", category: "UT/ST" },
  { id: "eternal_graved_great_sword", name: "Eternal Graved Great Sword", category: "UT/ST" },
  { id: "flail_gilded", name: "Gilded Chain Scythe", category: "UT/ST" },
  { id: "ao_hclay", name: "Henchman's Claymore", category: "UT/ST" },
  { id: "long_sword_1rarity", name: "Long Sword 1Rarity", category: "UT/ST" },
  { id: "long_sword_2rarity", name: "Long Sword 2Rarity", category: "UT/ST" },
  { id: "long_sword_3rarity", name: "Long Sword 3Rarity", category: "UT/ST" },
  { id: "long_sword_4rarity", name: "Long Sword 4Rarity", category: "UT/ST" },
  { id: "ao_bhd", name: "Bounty Hunter's Dagger", category: "UT/ST" },
  { id: "def_test_dagger", name: "Def Test Dagger", category: "UT/ST" },
  { id: "dag_evergreen", name: "Evergreen Dagger", category: "UT/ST" },
  { id: "duel_pirate", name: "Pirate's Sidearms", category: "UT/ST" },
  { id: "dag_righthook", name: "The Right Hook", category: "UT/ST" },
  { id: "bow_bow", name: "B.O.W.", category: "UT/ST" },
  { id: "bow_brilliance", name: "Brilliance Bow", category: "UT/ST" },
  { id: "bow_coralsoda", name: "Coral Soda", category: "UT/ST" },
  { id: "hi_frangible", name: "Frangible Longbow", category: "UT/ST" },
  { id: "bow_garland", name: "Garland Bow", category: "UT/ST" },
  { id: "bow_heartstruck", name: "Heartstruck Bow", category: "UT/ST" },
  { id: "bow_ignis", name: "Ignis", category: "UT/ST" },
  { id: "bow_leaf", name: "Leaf Bow", category: "UT/ST" },
  { id: "bow_occult", name: "Occult Bow", category: "UT/ST" },
  { id: "ao_pbow", name: "Predator Bow", category: "UT/ST" },
  { id: "bow_sacramental", name: "Sacramental Crossbow", category: "UT/ST" },
  { id: "bow_spidersilk", name: "Spider Silk Bow", category: "UT/ST" },
  { id: "bow_sunnyside", name: "Sunny Side Bow", category: "UT/ST" },
  { id: "bow_tectonus", name: "Tectonus", category: "UT/ST" },
  { id: "bow_thousand", name: "Thousand Shot", category: "UT/ST" },
  { id: "brass_chamberstick", name: "Brass Chamberstick", category: "UT/ST" },
  { id: "hi_macuahuitl", name: "Obsidian Macuahuitl", category: "UT/ST" },
  { id: "ao_twand", name: "Tyrant's Wand", category: "UT/ST" },
  { id: "wand_of_the_fallen", name: "Wand of the Fallen", category: "UT/ST" },
  { id: "bogwood_crook", name: "Bogwood Crook", category: "UT/ST" },
  { id: "ao_ostaff", name: "Oppressor's Staff", category: "UT/ST" },
  { id: "hi_sekhem", name: "Royal Sekhem", category: "UT/ST" },
  { id: "staff_staff", name: "S.T.A.F.F.", category: "UT/ST" },
  { id: "sleigh_bell_staff", name: "Sleigh Bell Staff", category: "UT/ST" },
  { id: "snow_branch", name: "Snow Branch", category: "UT/ST" },
  { id: "spring_rose", name: "Spring Rose", category: "UT/ST" },
  { id: "tezcacoatl_s_tail", name: "Tezcacoatl's Tail", category: "UT/ST" },
  { id: "ao_boa", name: "Blade of the Assailant", category: "UT/ST" },
  { id: "kat_bloodsiphon", name: "Blood Siphoning Katana", category: "UT/ST" },
  { id: "brambletooth_tachi", name: "Brambletooth Tachi", category: "UT/ST" },
  { id: "qbc_tachi", name: "Bunny Ear Tachi", category: "UT/ST" },
  { id: "kat_candy", name: "Candy Katana", category: "UT/ST" },
  { id: "kat_celestial", name: "Celestial Blade", category: "UT/ST" },
  { id: "hookblade_tachi", name: "Hookblade Tachi", category: "UT/ST" },
  { id: "kat_kyuuketsuki", name: "Kyuuketsuki Hitogoroshi", category: "UT/ST" },
  { id: "hi_khopesh", name: "Ritual Khopesh", category: "UT/ST" },
  { id: "kat_snowflake", name: "Snowflake Blade", category: "UT/ST" },
];

export const CATEGORIES: Category[] = [
  "T6 Ring",
  "T6 Ability",
  "T13 Weapon",
  "T13 Armor",
  "Potion",
  "Egg",
  "Consumable",
  "UT/ST",
];

export const ITEM_BY_ID = new Map(CATALOG.map((i) => [i.id, i]));
