import fs from "node:fs";
import path from "node:path";

export type EnchantEntry = {
  id: string;
  realmId: string;
  name: string;
  sprite: string;
};

let _byRealmId: Map<number, EnchantEntry> | null = null;

// Lazy-load the catalog the first time something asks for an entry.
// `realm-enchants.json` is at the repo root, generated by
// scripts/extract_enchants.mjs from rotmgenchants.txt.
function load(): Map<number, EnchantEntry> {
  if (_byRealmId) return _byRealmId;
  const p = path.join(process.cwd(), "realm-enchants.json");
  let raw: EnchantEntry[];
  try {
    raw = JSON.parse(fs.readFileSync(p, "utf8")) as EnchantEntry[];
  } catch {
    // No catalog present — every lookup returns null below. Pool UI will
    // just display the numeric ID instead of a name. Not fatal.
    _byRealmId = new Map();
    return _byRealmId;
  }
  _byRealmId = new Map();
  for (const e of raw) {
    const n = Number(e.realmId);
    if (Number.isFinite(n)) _byRealmId.set(n, e);
  }
  return _byRealmId;
}

export function enchantName(realmId: number): string | null {
  return load().get(realmId)?.name ?? null;
}

export function allEnchants(): EnchantEntry[] {
  return [...load().values()];
}
