
import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { VirtuosoGrid } from "react-virtuoso";
import TxForm from "./TxForm";
import RecentActivity from "./RecentActivity"
import { useLiveUpdates } from "@/lib/useLive"
import { applyPoolWire, emptyPoolState, instancesFromState, type PoolInstance, type PoolState, type PoolWire, type Rarity } from "@/lib/poolWire";
import LoginPanel from "./LoginPanel";
import WishlistPanel from "./WishlistPanel";
import TradePanel from "./TradePanel";
import OpenRequests from "./OpenRequests";
import PlayerName from "./PlayerName";
import { ItemSprite } from "./ItemSprite";
import { FilterRail, type ConsumableKind } from "./FilterRail";
import { TagSearch, matchesTags, effectsOfEnchant, type SearchTag, type Suggestions } from "./TagSearch";
import itemIndex from "@/lib/item-index.json";
import itemTooltips from "@/lib/item-tooltips.json";
import enchantMods from "@/lib/enchant-mods.json";
import { WITHDRAW_SERVERS } from "@/lib/servers";
import { serverOffLabel, useServerControls } from "@/lib/useServerControls";

// Normalized item name → { classes, slot }, generated from realm-items.json by
// scripts/build-class-index.mjs. Same name normalization as ItemSprite so pool
// instances resolve consistently.
type Dismantle = {
  common: number | null;
  rare: number | null;
  legendary: number | null;
  mythical: number | null;
};
type ItemMeta = {
  classes: string[] | null;
  slot: string | null;
  dismantle?: Dismantle | null;
  feedPower?: number | null;
};
const ITEM_INDEX = itemIndex as Record<string, ItemMeta>;

// Generated by scripts/build-item-tooltips.mjs from the client's equip.xml.
type ItemTooltip = {
  t: string | null; // tier badge: T13, UT, ST
  k: string; // kind: Staff, Heavy Armor, …
  c: string[]; // usable classes, ["ALL"] for everyone
  d: string; // description
  a?: { dmg: [number, number]; shots: number; rof: number; range: number; arc?: number; burst?: number }[];
  p?: string[]; // projectile traits
  e?: { s: string; v: number; r?: string; pct?: boolean }[]; // on equip
  mp?: number; mpe?: number; mps?: number; cd?: number;
  l?: string[]; // effect lines
  x?: { n: string; d: string }[]; // the game's own extra tooltip text
  xp?: number; fp?: number; set?: string; cons?: boolean;
};
const ITEM_TOOLTIPS = itemTooltips as unknown as Record<string, ItemTooltip>;

// Stat changes an enchantment makes to the item it sits on, keyed by the
// enchant's numeric type (scripts/build-item-tooltips.mjs, from enchantments.xml).
type EnchantMods = {
  e?: { s: string; v: number }[]; // flat on-equip stats
  dmg?: [number, number]; // min/max damage multipliers
  rof?: number; rng?: number; mp?: number; // multipliers
  xp?: number; // extra XP bonus points
  t?: string; // stat effects that depend on the player, as the game words them
};
const ENCHANT_MODS = enchantMods as unknown as Record<string, EnchantMods>;

const round1 = (n: number) => Math.round(n * 10) / 10;

// Fold the instance's enchantments into the item's numbers. Returns the
// merged view plus which fields changed, so the card can highlight them.
function applyEnchants(t: ItemTooltip, enchantIds: number[]) {
  const mods = enchantIds.map((id) => ENCHANT_MODS[String(id)]).filter((m): m is EnchantMods => !!m);
  const stats = new Map<string, { base: number; bonus: number }>();
  for (const e of t.e ?? []) if (!e.r && !e.pct) stats.set(e.s, { base: e.v, bonus: 0 });
  let dmg: [number, number] = [1, 1], rof = 1, rng = 1, mp = 1, xp = 0;
  const lines: string[] = [];
  for (const m of mods) {
    for (const e of m.e ?? []) {
      const cur = stats.get(e.s) ?? { base: 0, bonus: 0 };
      cur.bonus += e.v;
      stats.set(e.s, cur);
    }
    if (m.dmg) dmg = [dmg[0] * m.dmg[0], dmg[1] * m.dmg[1]];
    if (m.rof) rof *= m.rof;
    if (m.rng) rng *= m.rng;
    if (m.mp) mp *= m.mp;
    if (m.xp) xp += m.xp;
    if (m.t) lines.push(m.t);
  }
  return { stats, dmg, rof, rng, mp, xp, lines, any: mods.length > 0 };
}
const normName = (n: string) =>
  n.replace(/^(UT|ST|T\d+)\.\s+/, "").toLowerCase().trim();

// True if `itemName` is gear usable by `cls`. All-class gear (rings, ["ALL"])
// passes for every class. Consumables (potions, eggs, incantations) have no
// slot and are hidden when a class filter is active — the game data tags
// eggs as all-class, but nobody picking "Wizard" wants a page of eggs. They
// get their own rail buttons instead.
function itemUsableByClass(itemName: string, cls: string): boolean {
  const meta = ITEM_INDEX[normName(itemName)];
  if (!meta?.classes || !meta.slot) return false;
  return meta.classes.includes("ALL") || meta.classes.includes(cls);
}

// Catalog category a consumable-rail button stands for.
const CONSUMABLE_CATEGORY: Record<ConsumableKind, string> = { potion: "Potion", egg: "Egg" };

// True if `itemName` sits in the given slot (weapon/ability/armor/ring).
function itemInSlot(itemName: string, slot: string): boolean {
  return ITEM_INDEX[normName(itemName)]?.slot === slot;
}

// Forge dismantle value for an item (UT/ST only), or null if it has none.
function itemDismantle(itemName: string): Dismantle | null {
  return ITEM_INDEX[normName(itemName)]?.dismantle ?? null;
}

// Pet feed power for an item (0 if none / unknown).
function itemFeedPower(itemName: string): number {
  return ITEM_INDEX[normName(itemName)]?.feedPower ?? 0;
}

// Feed-power slider steps for a set of item names: 0 plus every distinct feed
// value those items have, ascending. Built from the catalog so the slider snaps
// only to values depositable items actually take.
function feedStepsFor(names: string[]): number[] {
  const s = new Set<number>([0]);
  for (const n of names) {
    const fp = itemFeedPower(n);
    if (fp > 0) s.add(fp);
  }
  return [...s].sort((a, b) => a - b);
}

// Forge material tiers, ordered high → low for display, with their icons.
const FORGE_TIERS = [
  { key: "mythical", label: "Mythical Material", icon: "/forge/mythical.png" },
  { key: "legendary", label: "Legendary Material", icon: "/forge/legendary.png" },
  { key: "rare", label: "Rare Material", icon: "/forge/rare.png" },
  { key: "common", label: "Common Material", icon: "/forge/common.png" },
] as const;

// --- Material slider model -------------------------------------------------
// The dismantle sliders filter to items yielding at least X of each material.
// Steps snap to amounts that actually exist, and the sliders constrain each
// other so the selected thresholds always match at least one real item:
//   - mythical items carry no common/rare, so raising mythical clears both
//     (and raising common/rare clears mythical);
//   - common and rare are coupled, so raising one drops the other to the
//     highest amount some item still satisfies.

type MatKey = "common" | "rare" | "legendary" | "mythical";
export type MatFilter = Record<MatKey, number>;
// Low → high tier order; also the tie-break order when reducing sliders.
const MAT_ORDER: MatKey[] = ["common", "rare", "legendary", "mythical"];

// Every item's material yield as a dense vector (missing tier = 0).
const DISMANTLE_ITEMS = Object.values(ITEM_INDEX)
  .map((m) => m.dismantle)
  .filter((d): d is Dismantle => !!d)
  .map((d) => ({
    common: d.common ?? 0,
    rare: d.rare ?? 0,
    legendary: d.legendary ?? 0,
    mythical: d.mythical ?? 0,
  }));

// Snap steps for a material: 0 plus every distinct amount that exists, ascending.
const matSteps = (key: MatKey): number[] => {
  const s = new Set<number>([0]);
  for (const it of DISMANTLE_ITEMS) if (it[key] > 0) s.add(it[key]);
  return [...s].sort((a, b) => a - b);
};
const MAT_STEPS: Record<MatKey, number[]> = {
  common: matSteps("common"),
  rare: matSteps("rare"),
  legendary: matSteps("legendary"),
  mythical: matSteps("mythical"),
};

// True if some real item meets every material threshold at once.
const feasibleMat = (f: MatFilter) =>
  DISMANTLE_ITEMS.some((it) => MAT_ORDER.every((k) => it[k] >= f[k]));

const prevStep = (key: MatKey, v: number): number => {
  const steps = MAT_STEPS[key];
  const i = steps.indexOf(v);
  return i > 0 ? steps[i - 1] : 0;
};

// Smallest positive amount of `key` among `items` (0 if none carry it).
const floorPositive = (
  items: { common: number; rare: number; legendary: number; mythical: number }[],
  key: MatKey,
): number => {
  let min = Infinity;
  for (const it of items) if (it[key] > 0) min = Math.min(min, it[key]);
  return min === Infinity ? 0 : min;
};
// True if every item carries `key`.
const allHave = (
  items: { common: number; rare: number; legendary: number; mythical: number }[],
  key: MatKey,
): boolean => items.length > 0 && items.every((it) => it[key] > 0);

// After moving slider `moved`, adjust the common/rare/legendary sliders so the
// combination matches the items still visible, keeping the just-moved slider
// fixed. Using the forge tier order (common < rare < legendary):
//   - LOWER tiers snap to the floor amount those items share — the guaranteed
//     minimum you'd get (e.g. raising rare pulls common up to the tier's floor);
//   - a HIGHER tier engages only when EVERY visible item carries it (so raising
//     rare to the level where only the rare+legendary item remains lights up
//     legendary, but ordinary rare tiers leave it off);
//   - mythical is disjoint from all three, so touching it clears them (and vice
//     versa).
function reconcileMat(next: MatFilter, moved: MatKey): MatFilter {
  const r = { ...next };

  if (moved === "mythical") {
    if (r.mythical > 0) { r.common = 0; r.rare = 0; r.legendary = 0; }
    return r;
  }
  if (r.mythical > 0) r.mythical = 0; // engaging any other tier clears mythical

  const v = r[moved];
  if (v > 0) {
    const vis = DISMANTLE_ITEMS.filter((it) => it[moved] >= v);
    const movedTier = MAT_ORDER.indexOf(moved);
    for (const j of ["common", "rare", "legendary"] as const) {
      if (j === moved) continue;
      const lower = MAT_ORDER.indexOf(j) < movedTier;
      r[j] = lower || allHave(vis, j) ? floorPositive(vis, j) : 0;
    }
  }

  // Safety net: reduce the largest non-moved slider until the combo is real.
  let guard = 0;
  while (!feasibleMat(r) && guard++ < 40) {
    let pick: MatKey | null = null;
    for (const k of MAT_ORDER) {
      if (k === moved || r[k] <= 0) continue;
      if (pick === null || r[k] > r[pick]) pick = k;
    }
    if (pick === null) break;
    r[pick] = prevStep(pick, r[pick]);
  }
  return r;
}

// True if the item's dismantle yield meets every active material threshold.
// In exact mode the yield must equal the sliders on every tier, so "exactly 0"
// of everything selects items that don't dismantle at all.
function passesMaterials(itemName: string, f: MatFilter, exact: boolean): boolean {
  if (!exact && MAT_ORDER.every((k) => f[k] === 0)) return true;
  const d = itemDismantle(itemName);
  return MAT_ORDER.every((k) => (exact ? (d?.[k] ?? 0) === f[k] : (d?.[k] ?? 0) >= f[k]));
}

// Threshold check shared by the feed-power and enchant-slot filters: "at
// least" by default (0 = off), or "exactly" when the label has been toggled.
function passesMin(actual: number, min: number, exact: boolean): boolean {
  return exact ? actual === min : min === 0 || actual >= min;
}

// The value label next to each slider. Clicking it flips the slider between
// "X or more" and "exactly X".
function SliderValue({
  className,
  amount,
  exact,
  onToggle,
}: {
  className: string;
  amount: number;
  exact: boolean;
  onToggle: () => void;
}) {
  return (
    <button
      type="button"
      className={`${className} slider-val-toggle`}
      aria-pressed={exact}
      title={exact ? "Click to match this amount or more" : "Click to match exactly this amount"}
      onClick={onToggle}
    >
      {exact ? `exactly ${amount}` : `${amount} or more`}
    </button>
  );
}

// "potions" is a withdraw variant: same endpoint, but sized in stat points
// instead of picked item-by-item. It keeps the grid on the withdraw view so
// the player can still see what stock backs their request. "claim" takes the
// tray into personal storage (pool tabs); "donate" hands vault items back to
// the pool (My vault tab).
export type Tab = "deposit" | "withdraw" | "potions" | "claim" | "donate";

// The instance record and rarity grade come from the wire module the server
// shares (lib/poolWire.ts); re-exported for the components that import them
// from here.
export type { PoolInstance, Rarity };

export type PoolKind = "seasonal" | "nonseasonal" | "myvault" | "wishlist";

// GET /api/vault: the logged-in account's personal storage.
export type VaultItemView = {
  instanceId: string;
  itemId: string;
  itemName: string;
  enchantments: { id: number; name: string | null }[];
  rarity: Rarity;
  seasonal: boolean;
  botGuid: string;
  botIgn: string;
  server: string;
  online: boolean;
  inTransit: boolean;
  reserved: boolean;
  lost: boolean;
  source: "claim" | "deposit";
  since: number;
};
// One of the account's two vaults: the seasonal or the non-seasonal half.
export type VaultHalfView = {
  seasonal: boolean;
  slots: number;
  used: number;
  wishes: number;
  bot: { guid: string; ign: string; server: string; online: boolean } | null;
};
export type VaultView = {
  total: number;
  block: number;
  unallocated: number;
  seasonal: VaultHalfView;
  nonseasonal: VaultHalfView;
  items: VaultItemView[];
  live: boolean;
};
export type VaultHalfKind = "seasonal" | "nonseasonal";

const MAX_TRAY = 4;
/** An offer can give up to a full trade window. */
const MAX_TRADE_TRAY = 24;


const RARITY_COLOR: Record<Rarity, string> = {
  common: "transparent",
  uncommon: "#6ec46e",
  rare: "#5aa6ff",
  legendary: "#d4a13b",
  divine: "#e26ad9",
};

// A stack of physically identical instances: same item type, same enchant
// set (or none), same server. The withdraw grid shows one tile per stack
// with a count instead of one tile per instance; each click adds one more
// copy to the tray. `rep` is any member — they're interchangeable.
type Stack = {
  key: string;
  rep: PoolInstance;
  instances: PoolInstance[];
  botIgns: string[];
  // True when the stack folds together instances with different enchant sets
  // (the "stack by rarity & type" checkbox). The tooltip then shows the base
  // item instead of one arbitrary member's enchants.
  mixed: boolean;
};

type HoverState = { stack: Stack; rect: DOMRect } | null;

type CatalogEntry = {
  itemId: string;
  itemName: string;
  sprite: string | null;
  // Category ("T13 Weapon", "Potion", …) and optional subtype ("Sword",
  // "Ring", …) from the server catalog. Drive the filter chips and, via a
  // by-itemId lookup, per-instance filtering in the withdraw grid.
  category: string;
  subtype: string | null;
  // Leaderboard points one unenchanted unit earns when deposited, under
  // the current pricing epoch (server-computed).
  points: number;
};

// Sort orders offered above the grid. "default" keeps the server order
// (item type, then instance) for withdraw and name order for deposit.
// "stat:X" orders by how much of stat X the item gives on equip (enchant
// bonuses included on the withdraw grid).
const STAT_SORTS = ["ATT", "DEF", "SPD", "DEX", "VIT", "WIS", "HP", "MP"] as const;
type StatSort = (typeof STAT_SORTS)[number];
type SortKey = "feed" | "qty" | "points" | "rarity" | `stat:${StatSort}`;

const SORT_LABELS: Record<Exclude<SortKey, `stat:${StatSort}`>, string> = {
  feed: "Feed Power",
  qty: "Quantity",
  points: "Points",
  rarity: "Slots",
};
const STAT_SORT_LABELS: Record<StatSort, string> = {
  ATT: "Attack", DEF: "Defense", SPD: "Speed", DEX: "Dexterity", VIT: "Vitality", WIS: "Wisdom", HP: "HP", MP: "MP",
};

// Flat on-equip total of one stat for an item with the given enchantments.
// Items without tooltip data count as 0.
function statTotal(itemName: string, enchantIds: number[], which: StatSort): number {
  const t = ITEM_TOOLTIPS[normName(itemName)];
  if (!t) return 0;
  const totals = new Map<string, number>();
  for (const e of t.e ?? []) if (!e.r && !e.pct) totals.set(e.s, (totals.get(e.s) ?? 0) + e.v);
  for (const id of enchantIds) for (const e of ENCHANT_MODS[String(id)]?.e ?? []) totals.set(e.s, (totals.get(e.s) ?? 0) + e.v);
  return totals.get(which) ?? 0;
}
const statSortOf = (sort: SortKey): StatSort | null => (sort.startsWith("stat:") ? (sort.slice(5) as StatSort) : null);

// Rarity rank for the "rarity" sort (high → low).
const RARITY_RANK: Record<Rarity, number> = {
  common: 0,
  uncommon: 1,
  rare: 2,
  legendary: 3,
  divine: 4,
};

export default function Vault() {
  const [instances, setInstances] = useState<PoolInstance[]>([]);
  // The pool as last applied: revision plus per-bot slots (lib/poolWire.ts).
  // A refresh asks the server for the delta since `rev`, and `instances` is
  // re-derived from the patched state for the grid.
  const poolState = useRef<PoolState>(emptyPoolState());
  // A refresh that came due while the tab was hidden; run once it is visible again.
  const poolRefreshDeferred = useRef(false);
  // Full catalog from the API — used by the deposit-mode aggregate to
  // surface items the pool accepts even when current stock is 0. The
  // aggregate seeds itself from this list and fills in counts from
  // `instances` so empty rows render as ×0 instead of being hidden.
  const [catalog, setCatalog] = useState<CatalogEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [poolErr, setPoolErr] = useState<string | null>(null);
  // Two refresh signals, because they cost very different amounts.
  // poolKey refetches /api/pool — the whole fleet's inventory, ~300ms.
  // feedKey only repaints Recent Activity and the leaderboard. A trade
  // changes both; saving a name effect changes only the names in the feeds,
  // and must not re-download the pool to recolour one row.
  const [poolKey, setPoolKey] = useState(0);
  const [feedKey, setFeedKey] = useState(0);
  // Default to withdraw — most users come back to claim items they already
  // deposited, not to deposit more, so opening on withdraw saves a click.
  const [tab, setTab] = useState<Tab>("withdraw");
  // Seasonal / non-seasonal are disjoint economies (a seasonal char can
  // only trade seasonal players), so the page shows one at a time.
  const [pool, setPool] = useState<PoolKind>("seasonal");
  // The pool tab to return to from My vault (the bookmark tabs switch between
  // the two; the pool's own sub-tabs live under the Pool bookmark).
  const [lastPoolKind, setLastPoolKind] = useState<Exclude<PoolKind, "myvault" | "wishlist">>("seasonal");
  // My Vault shows one half at a time — an account has a seasonal and a
  // non-seasonal vault, each on its own bot.
  const [vaultHalf, setVaultHalf] = useState<VaultHalfKind>("seasonal");
  const vaultHalfTouched = useRef(false);
  // Trades: the pool grid stays as the picker, the tray feeds an offer instead of a withdraw.
  const [tradeMode, setTradeMode] = useState(false);
  const view: "pool" | "vault" | "wishlist" | "trades" = pool === "myvault" ? "vault" : pool === "wishlist" ? "wishlist" : tradeMode ? "trades" : "pool";
  const maxTray = tradeMode ? MAX_TRADE_TRAY : MAX_TRAY;
  const [tray, setTray] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  // Search tags (item / enchantment / effect chips) picked from the search
  // box's suggestions. Free text in `query` still narrows on top of them.
  const [tags, setTags] = useState<SearchTag[]>([]);
  // Class + slot filters driven by the left-side filter rail. null = no filter;
  // when both are set they combine (class AND slot).
  const [classFilter, setClassFilter] = useState<string | null>(null);
  const [slotFilter, setSlotFilter] = useState<string | null>(null);
  // Consumables aren't gear: this filter and the class/slot pair are mutually
  // exclusive, so picking either side clears the other.
  const [consumableFilter, setConsumableFilter] = useState<ConsumableKind | null>(null);
  const selectClass = useCallback((cls: string | null) => {
    setClassFilter(cls);
    if (cls) setConsumableFilter(null);
  }, []);
  const selectSlot = useCallback((slot: string | null) => {
    setSlotFilter(slot);
    if (slot) setConsumableFilter(null);
  }, []);
  const selectConsumable = useCallback((kind: ConsumableKind | null) => {
    setConsumableFilter(kind);
    if (kind) {
      setClassFilter(null);
      setSlotFilter(null);
    }
  }, []);
  // Dismantle-material thresholds (0 = off). Sliders snap to existing amounts
  // and constrain each other via reconcileMat.
  const [matFilter, setMatFilter] = useState<MatFilter>({ common: 0, rare: 0, legendary: 0, mythical: 0 });
  const onMatChange = useCallback((key: MatKey, amount: number) => {
    setMatFilter((cur) => reconcileMat({ ...cur, [key]: amount }, key));
  }, []);
  // "Exactly" toggles: the material sliders share one (a dismantle yield is a
  // vector, so exact means the whole vector); feed and slots have their own.
  const [matExact, setMatExact] = useState(false);
  const [feedExact, setFeedExact] = useState(false);
  const [enchExact, setEnchExact] = useState(false);
  const toggleMatExact = useCallback(() => setMatExact((v) => !v), []);
  const toggleFeedExact = useCallback(() => setFeedExact((v) => !v), []);
  const toggleEnchExact = useCallback(() => setEnchExact((v) => !v), []);
  // Feed-power minimum (0 = off). Independent of the forge material sliders.
  const [feedMin, setFeedMin] = useState(0);
  // Slider steps come from the catalog (depositable items) so it snaps only to
  // feed values items in the pool can actually have.
  const feedSteps = useMemo(() => feedStepsFor(catalog.map((c) => c.itemName)), [catalog]);
  // Minimum enchant slots (applied enchantments) an instance must have (0 = off).
  const [enchMin, setEnchMin] = useState(0);
  const [sort, setSort] = useState<SortKey>("feed");
  // "Stack by rarity & type": fold every instance of one item type and
  // rarity into a single withdraw tile, ignoring enchant differences.
  const [stackByType, setStackByType] = useState(false);
  // Tooltip is portaled to <body> with position: fixed so the scrollable
  // .pool-grid-wrap can't clip it. Tile reports its bounding rect on hover;
  // we render once at the top level.
  const [hover, setHover] = useState<HoverState>(null);
  // Enchant catalog (realm-enchants.json, ~150 KB) for sprite + name
  // rendering inside the hover tooltip. Loaded once on mount.
  const [enchSprites, setEnchSprites] = useState<Map<number, string>>(new Map());
  // The grid is virtualized (VirtuosoGrid) so thousands of tiles only mount
  // ~a screenful of DOM nodes. It scrolls against the existing .pool-grid-wrap
  // (kept as the scroll parent so the themed scrollbar + layout are unchanged);
  // a callback ref hands Virtuoso that element once it mounts.
  const [scrollParent, setScrollParent] = useState<HTMLElement | null>(null);
  // Verified session IGN (or null). Sourced once from the cookie via
  // /api/login/me and updated by the LoginPanel; the trade form reads it
  // instead of the old free-text field.
  const [sessionIgn, setSessionIgn] = useState<string | null>(null);
  // Operator-granted features on the account (see lib/features.ts); "wishlist"
  // is what shows the My Wishlist bookmark.
  const [features, setFeatures] = useState<string[]>([]);
  // The account's personal storage, for the My vault tab. Refetched on every
  // pool/feed refresh while that tab is open, and whenever a vault action
  // completes (vaultKey).
  const [vault, setVault] = useState<VaultView | null>(null);
  const [vaultErr, setVaultErr] = useState<string | null>(null);
  const [vaultKey, setVaultKey] = useState(0);
  const bumpVault = useCallback(() => setVaultKey((k) => k + 1), []);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/login/me")
      .then((r) => r.json())
      .then((d: { ign: string | null; features?: string[] }) => {
        if (cancelled) return;
        setSessionIgn(d.ign ?? null);
        setFeatures(d.features ?? []);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, []);
  // Logging in, switching or linking a character can change what the
  // account is entitled to; ask again rather than trust the old answer.
  const onSessionChange = useCallback((ign: string | null) => {
    setSessionIgn(ign);
    if (!ign) {
      setFeatures([]);
      return;
    }
    fetch("/api/login/me")
      .then((r) => r.json())
      .then((d: { features?: string[] }) => setFeatures(d.features ?? []))
      .catch(() => {});
  }, []);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/enchant-catalog")
      .then((r) => r.json())
      .then((data: { enchants: { realmId: string; sprite: string }[] }) => {
        if (cancelled) return;
        const m = new Map<number, string>();
        for (const e of data.enchants ?? []) {
          const id = Number(e.realmId);
          if (Number.isFinite(id) && e.sprite) m.set(id, e.sprite);
        }
        setEnchSprites(m);
      })
      .catch(() => {
        // Tooltip renders without icons — names still work.
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // Rarity sort is per-instance, so it's hidden on the deposit tab. If the
  // user picked it in withdraw then switched, drop back to default so the
  // sort <select> doesn't render a value with no matching option.
  useEffect(() => {
    if (tab === "deposit" && sort === "rarity") setSort("feed");
  }, [tab, sort]);

  const reload = useCallback(() => {
    setPoolKey((k) => k + 1);
    setFeedKey((k) => k + 1);
  }, []);
  const reloadFeeds = useCallback(() => setFeedKey((k) => k + 1), []);
  const reloadPool = useCallback(() => setPoolKey((k) => k + 1), []);

  // Live updates: the same two signals the local user's own trade bumps, but
  // driven by everyone else's activity via /api/live. A trade anywhere repaints
  // Recent Activity and the leaderboard; a change in the fleet's inventory
  // repaints the grid. The pool refetch is answered from the server's shared
  // snapshot, so this stays cheap no matter how many people have the page open.
  useLiveUpdates({ onTx: reloadFeeds, onPool: reloadPool });

  useEffect(() => {
    // A hidden tab does not download the pool; the refresh runs on
    // visibilitychange (below). Background tabs were most of the pool traffic.
    if (typeof document !== "undefined" && document.visibilityState === "hidden") {
      poolRefreshDeferred.current = true;
      return;
    }
    const ctrl = new AbortController();
    const st = poolState.current;
    // `v=2` marks a page that speaks this format; a tab from before the
    // format changed sends neither it nor `since`, and the server answers
    // that one with a short "reload" note instead of the whole pool.
    const url = st.rev ? `/api/pool?since=${encodeURIComponent(st.rev)}` : "/api/pool?v=2";
    fetch(url, { cache: "no-store", signal: ctrl.signal })
      .then((r) => r.json())
      .then((data: PoolWire & { error?: string }) => {
        if (ctrl.signal.aborted) return;
        if (data.v !== 2) {
          setPoolErr("unexpected pool format");
          setLoading(false);
          return;
        }
        const result = applyPoolWire(st, data);
        if (result === "mismatch") {
          // The server could not describe the change since our revision (a
          // restart, or this tab fell too far behind): start over in full.
          st.rev = null;
          setPoolKey((k) => k + 1);
          return;
        }
        if (data.full) {
          setCatalog(data.catalog ?? []);
          setPoolErr(data.error ?? null);
        } else if (data.catalog) {
          setCatalog(data.catalog);
        }
        if (result !== "unchanged") setInstances(instancesFromState(st));
        setLoading(false);
      })
      .catch((e: Error) => {
        if (ctrl.signal.aborted) return;
        // Without this catch the UI sits on "Loading…" forever on any
        // network failure. Surface it so the user knows; what was already
        // loaded stays on screen.
        setPoolErr(`fetch failed: ${e.message}`);
        setLoading(false);
      });
    // A refresh that starts before this one answered makes it moot: drop it
    // rather than let several downloads race.
    return () => ctrl.abort();
  }, [poolKey]);

  useEffect(() => {
    if (typeof document === "undefined") return;
    const onVisible = () => {
      if (document.visibilityState !== "visible" || !poolRefreshDeferred.current) return;
      poolRefreshDeferred.current = false;
      setPoolKey((k) => k + 1);
    };
    document.addEventListener("visibilitychange", onVisible);
    return () => document.removeEventListener("visibilitychange", onVisible);
  }, []);

  useEffect(() => {
    if (!sessionIgn) {
      setVault(null);
      return;
    }
    let cancelled = false;
    fetch("/api/vault", { cache: "no-store" })
      .then(async (r) => {
        const d = await r.json();
        if (cancelled) return;
        if (!r.ok) {
          setVaultErr(d.error ?? `HTTP ${r.status}`);
          return;
        }
        setVaultErr(null);
        setVault(d as VaultView);
        // Land on the half that has slots until the player picks one.
        if (!vaultHalfTouched.current) {
          const v = d as VaultView;
          if (v.seasonal.slots === 0 && v.nonseasonal.slots > 0) setVaultHalf("nonseasonal");
        }
      })
      .catch((e: Error) => {
        if (!cancelled) setVaultErr(e.message);
      });
    return () => {
      cancelled = true;
    };
    // poolKey/feedKey: a trade or a fleet move changes where items are.
  }, [sessionIgn, vaultKey, poolKey, feedKey]);

  // Everything below the tab bar sees only the active pool's instances. The
  // My vault tab shows the account's own items in the same tile shape, so the
  // filters, sort, stacks and tray all work unchanged.
  const poolInstances = useMemo<PoolInstance[]>(() => {
    if (pool === "myvault") {
      return (vault?.items ?? []).filter((v) => v.seasonal === (vaultHalf === "seasonal")).map((v) => ({
        instanceId: v.instanceId,
        itemId: v.itemId,
        itemName: v.itemName,
        sprite: null,
        botGuid: v.botGuid,
        botIgn: v.botIgn,
        server: v.server,
        seasonal: v.seasonal,
        enchantments: v.enchantments,
        rarity: v.rarity,
      }));
    }
    return instances.filter((i) => i.seasonal === (pool === "seasonal"));
  }, [instances, pool, vault, vaultHalf]);

  const trayInstances = useMemo(
    () => tray.map((id) => poolInstances.find((i) => i.instanceId === id) ?? null),
    [tray, poolInstances],
  );

  // Switching pools clears the tray — a withdraw can't mix bots from both
  // economies, and stale cross-pool picks would 404 anyway.
  // The whole site's accent follows the view: gold for the pool, pastel blue
  // for personal storage (see :root[data-view="vault"] in globals.css).
  useEffect(() => {
    document.documentElement.dataset.view = view;
    return () => {
      delete document.documentElement.dataset.view;
    };
  }, [view]);

  const switchPool = useCallback((next: PoolKind, trades = false) => {
    setPool(next);
    if (next !== "myvault" && next !== "wishlist") setLastPoolKind(next);
    setTradeMode(trades && next !== "myvault" && next !== "wishlist");
    setTray([]);
    // Claim and potions belong to the pool tabs, donate to My vault; land on
    // withdraw when the current tab has no meaning where we're going.
    setTab((t) => (next === "myvault" ? (t === "claim" || t === "potions" ? "withdraw" : t) : t === "donate" ? "withdraw" : t));
  }, []);

  // Switching halves clears the tray too: the two vaults ride different bots.
  const switchVaultHalf = useCallback((next: VaultHalfKind) => {
    vaultHalfTouched.current = true;
    setVaultHalf(next);
    setTray([]);
  }, []);

  // Give a half more (or fewer) of the account's slots, a block at a time.
  const [vaultAllocBusy, setVaultAllocBusy] = useState(false);
  const allocateVault = useCallback(async (seasonal: boolean, slots: number) => {
    setVaultAllocBusy(true);
    try {
      const r = await fetch("/api/vault/allocate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ seasonal, slots }),
      });
      const d = await r.json();
      if (!r.ok) setVaultErr(d.error ?? `HTTP ${r.status}`);
      else setVaultErr(null);
      setVaultKey((k) => k + 1);
    } catch (e) {
      setVaultErr((e as Error).message);
    } finally {
      setVaultAllocBusy(false);
    }
  }, []);

  // The vault half the page is looking at (or, on a pool tab, the one a
  // claim from that tab would fill).
  const ctxSeasonal = pool === "myvault" ? vaultHalf === "seasonal" : pool === "seasonal";
  const ctxHalf = vault ? (ctxSeasonal ? vault.seasonal : vault.nonseasonal) : null;

  // Adds one not-yet-picked member of a stack. The pick happens inside
  // the functional update so back-to-back clicks each grab a DIFFERENT
  // instance even before React re-renders between them. Stacks can span
  // servers (the group key ignores server), so prefer a copy that matches
  // the servers already in the tray — a withdraw must be single-server,
  // and offline copies (server "") are wildcards.
  const addFromStack = useCallback((stackInstances: PoolInstance[]) => {
    setTray((prev) => {
      if (prev.length >= maxTray) return prev;
      const prevSet = new Set(prev);
      let candidates = stackInstances.filter((i) => !prevSet.has(i.instanceId));
      if (candidates.length === 0) return prev;
      if (tradeMode && prev.length) {
        // One offer trades from one account: prefer a copy on the bot already in the tray.
        const bot = instances.find((i) => i.instanceId === prev[0])?.botGuid;
        const same = candidates.filter((i) => i.botGuid === bot);
        if (same.length) candidates = same;
      }
      const trayServers = new Set(
        prev
          .map((id) => instances.find((i) => i.instanceId === id)?.server)
          .filter(Boolean),
      );
      const match =
        trayServers.size === 0
          ? candidates[0]
          : candidates.find((i) => !i.server || trayServers.has(i.server)) ??
            candidates[0];
      return [...prev, match.instanceId];
    });
  }, [instances, maxTray, tradeMode]);

  const removeFromTrayAt = useCallback((index: number) => {
    setTray((prev) => prev.filter((_, i) => i !== index));
  }, []);

  const clearTray = useCallback(() => setTray([]), []);

  // itemId → deposit points, for the "points" sort in the withdraw grid
  // (stacks carry no points field of their own).
  const catalogPoints = useMemo(() => {
    const m = new Map<string, number>();
    for (const c of catalog) m.set(c.itemId, c.points ?? 0);
    return m;
  }, [catalog]);
  // itemId → category, for the consumable rail in the withdraw grid.
  const catalogCategory = useMemo(() => {
    const m = new Map<string, string>();
    for (const c of catalog) m.set(c.itemId, c.category);
    return m;
  }, [catalog]);

  // Filter for the grid: the class rail then a case-insensitive substring
  // match on item + enchant names (names are short enough that plain substring
  // feels right and stays fast).
  // Instances passing the rail + slider filters, before search tags or text.
  // Also the base the search box draws its suggestions from, so it only
  // offers tags that can still match something.
  const railFiltered = useMemo(
    () =>
      poolInstances.filter((inst) => {
        if (classFilter && !itemUsableByClass(inst.itemName, classFilter)) return false;
        if (slotFilter && !itemInSlot(inst.itemName, slotFilter)) return false;
        if (consumableFilter && catalogCategory.get(inst.itemId) !== CONSUMABLE_CATEGORY[consumableFilter]) return false;
        if (!passesMaterials(inst.itemName, matFilter, matExact)) return false;
        if (!passesMin(itemFeedPower(inst.itemName), feedMin, feedExact)) return false;
        if (!passesMin(inst.enchantments.length, enchMin, enchExact)) return false;
        return true;
      }),
    [poolInstances, classFilter, slotFilter, consumableFilter, catalogCategory, matFilter, matExact, feedMin, feedExact, enchMin, enchExact],
  );
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return railFiltered.filter((inst) => {
      if (!matchesTags(tags, inst.itemId, inst.enchantments)) return false;
      if (!q) return true;
      if (inst.itemName.toLowerCase().includes(q)) return true;
      for (const e of inst.enchantments) {
        if (e.name && e.name.toLowerCase().includes(q)) return true;
      }
      return false;
    });
  }, [railFiltered, query, tags]);

  // What the search box may offer next. Items: anything still visible once
  // the non-item tags apply (item chips OR together, so a second item stays
  // offerable). Enchants and effects: only those carried by instances that
  // match EVERY current tag — pick "Doom Bow" and the list shrinks to the
  // enchants doom bows in the pool actually have. The deposit grid is
  // per-item, so there only item tags mean anything and only items are offered.
  const suggestions = useMemo<Suggestions>(() => {
    const nonItem = tags.filter((t) => t.kind !== "item");
    const itemTagIds = new Set(tags.filter((t) => t.kind === "item").map((t) => (t as { id: string }).id));
    const items = new Map<string, string>();
    if (tab === "deposit") {
      for (const c of catalog) {
        if (itemTagIds.has(c.itemId)) continue;
        if (classFilter && !itemUsableByClass(c.itemName, classFilter)) continue;
        if (slotFilter && !itemInSlot(c.itemName, slotFilter)) continue;
        if (consumableFilter && c.category !== CONSUMABLE_CATEGORY[consumableFilter]) continue;
        if (!passesMaterials(c.itemName, matFilter, matExact)) continue;
        if (!passesMin(itemFeedPower(c.itemName), feedMin, feedExact)) continue;
        items.set(c.itemId, c.itemName);
      }
      return { items: [...items].map(([id, name]) => ({ id, name })).sort((a, b) => a.name.localeCompare(b.name)), enchants: [], effects: [] };
    }
    for (const inst of railFiltered) {
      if (!itemTagIds.has(inst.itemId) && matchesTags(nonItem, inst.itemId, inst.enchantments)) items.set(inst.itemId, inst.itemName);
    }
    const taggedEnch = new Set(tags.filter((t) => t.kind === "ench").map((t) => (t as { name: string }).name));
    const taggedEff = new Set(tags.filter((t) => t.kind === "effect").map((t) => (t as { key: string }).key));
    const enchants = new Set<string>();
    const effects = new Set<string>();
    for (const inst of railFiltered) {
      if (!matchesTags(tags, inst.itemId, inst.enchantments)) continue;
      for (const e of inst.enchantments) {
        const name = e.name ?? `Enchant #${e.id}`;
        if (!taggedEnch.has(name)) enchants.add(name);
        for (const k of effectsOfEnchant(e.id)) if (!taggedEff.has(k)) effects.add(k);
      }
    }
    return {
      items: [...items].map(([id, name]) => ({ id, name })).sort((a, b) => a.name.localeCompare(b.name)),
      enchants: [...enchants].sort(),
      effects: [...effects].sort(),
    };
  }, [tab, tags, railFiltered, catalog, classFilter, slotFilter, consumableFilter, matFilter, matExact, feedMin, feedExact]);

  // Withdraw mode collapses identical instances — same item, same enchant
  // set (unenchanted counts as a set) — into one tile with a count, no
  // matter which bot or server holds each copy. Fewer tiles to scan when
  // most of the pool is duplicate stock. Clicking a stack adds ONE
  // not-yet-picked member to the tray each time.
  const stacks = useMemo<Stack[]>(() => {
    const byKey = new Map<string, Stack>();
    // Per-stack enchant key of the first member, to detect mixed stacks.
    const firstEnch = new Map<string, string>();
    for (const inst of filtered) {
      const enchKey = inst.enchantments
        .map((e) => e.id)
        .sort((a, b) => a - b)
        .join(",");
      // Stack-by-type collapses on item + rarity only, so differently
      // enchanted copies of the same item share one tile.
      const key = stackByType ? `${inst.itemId}|r:${inst.rarity}` : `${inst.itemId}|${enchKey}`;
      let s = byKey.get(key);
      if (!s) {
        s = { key, rep: inst, instances: [], botIgns: [], mixed: false };
        byKey.set(key, s);
        firstEnch.set(key, enchKey);
      } else if (!s.mixed && firstEnch.get(key) !== enchKey) {
        s.mixed = true;
      }
      s.instances.push(inst);
      if (inst.botIgn && !s.botIgns.includes(inst.botIgn)) s.botIgns.push(inst.botIgn);
    }
    const list = [...byKey.values()];
    // "default" keeps the server's item-type order (byKey preserves first-seen
    // order, which follows the already-sorted instance list).
    if (sort === "feed") {
      list.sort(
        (a, b) =>
          itemFeedPower(b.rep.itemName) - itemFeedPower(a.rep.itemName) ||
          a.rep.itemName.localeCompare(b.rep.itemName),
      );
    } else if (sort === "qty") {
      list.sort((a, b) => b.instances.length - a.instances.length);
    } else if (sort === "points") {
      const pts = (s: Stack) => catalogPoints.get(s.rep.itemId) ?? 0;
      list.sort((a, b) => pts(b) - pts(a));
    } else if (sort === "rarity") {
      list.sort((a, b) => RARITY_RANK[b.rep.rarity] - RARITY_RANK[a.rep.rarity]);
    } else if (statSortOf(sort)) {
      const which = statSortOf(sort)!;
      const total = (s: Stack) => statTotal(s.rep.itemName, s.rep.enchantments.map((e) => e.id), which);
      list.sort((a, b) => total(b) - total(a) || a.rep.itemName.localeCompare(b.rep.itemName));
    }
    return list;
  }, [filtered, sort, catalogPoints, stackByType]);

  // Deposit mode shows aggregate stock (one tile per CATALOG item with ×N
  // count). Seeded from the full catalog so items the pool accepts but is
  // currently out of show as ×0 — players know what's tradeable without
  // hunting through docs. Withdraw mode keeps per-instance tiles so the
  // user can click the exact +14 tome they want. Aggregate is computed
  // even on the withdraw tab so tab-switching is instant.
  type AggregateTile = {
    itemId: string;
    itemName: string;
    sprite: string | null;
    rarity: Rarity;
    count: number;
    points: number; // deposit value of one unenchanted unit, current epoch
    bots: string[]; // distinct bot IGNs holding any of this stack
  };
  const filteredAggregate = useMemo<AggregateTile[]>(() => {
    // Apply the same search filter to catalog names + (optionally) instance
    // enchant names. Item-name matches drive both the row visibility and
    // the count rollup.
    const q = query.trim().toLowerCase();
    const itemTagIds = new Set(tags.filter((t) => t.kind === "item").map((t) => (t as { id: string }).id));
    const catalogVisible = catalog.filter((c) => {
      if (itemTagIds.size > 0 && !itemTagIds.has(c.itemId)) return false;
      if (classFilter && !itemUsableByClass(c.itemName, classFilter)) return false;
      if (slotFilter && !itemInSlot(c.itemName, slotFilter)) return false;
      if (consumableFilter && c.category !== CONSUMABLE_CATEGORY[consumableFilter]) return false;
      if (!passesMaterials(c.itemName, matFilter, matExact)) return false;
      if (!passesMin(itemFeedPower(c.itemName), feedMin, feedExact)) return false;
      return q ? c.itemName.toLowerCase().includes(q) : true;
    });
    const byItem = new Map<string, AggregateTile>();
    for (const c of catalogVisible) {
      byItem.set(c.itemId, {
        itemId: c.itemId,
        itemName: c.itemName,
        sprite: c.sprite,
        points: c.points ?? 1,
        // Empty stock has no enchant tier — default rarity. Filled in below
        // if instances actually exist (the existing-stock rarity rule was
        // per-physical-item, so an aggregate doesn't have a single rarity;
        // we just use common for the frame).
        rarity: "common",
        count: 0,
        bots: [],
      });
    }
    // Fold in the live instances. We iterate the UNFILTERED instance list
    // for count accuracy: if the user searched for an item name, the search
    // filtered catalog visibility above, but every matching catalog entry
    // should still show its true total in-stock count.
    for (const inst of poolInstances) {
      const cur = byItem.get(inst.itemId);
      if (!cur) continue; // search filtered this item type out
      cur.count += 1;
      if (inst.botIgn && !cur.bots.includes(inst.botIgn)) cur.bots.push(inst.botIgn);
    }
    const list = [...byItem.values()];
    // The sort control can reorder by feed power, stock count, or deposit value.
    // Rarity has no meaning for an aggregate (a stack spans tiers) and "default"
    // both fall back to name order.
    if (sort === "feed") {
      list.sort(
        (a, b) =>
          itemFeedPower(b.itemName) - itemFeedPower(a.itemName) ||
          a.itemName.localeCompare(b.itemName),
      );
    } else if (sort === "qty") {
      list.sort((a, b) => b.count - a.count || a.itemName.localeCompare(b.itemName));
    } else if (sort === "points") {
      list.sort((a, b) => b.points - a.points || a.itemName.localeCompare(b.itemName));
    } else if (statSortOf(sort)) {
      const which = statSortOf(sort)!;
      list.sort((a, b) => statTotal(b.itemName, [], which) - statTotal(a.itemName, [], which) || a.itemName.localeCompare(b.itemName));
    } else {
      list.sort((a, b) => a.itemName.localeCompare(b.itemName));
    }
    return list;
  }, [catalog, poolInstances, query, tags, sort, classFilter, slotFilter, consumableFilter, matFilter, matExact, feedMin, feedExact]);

  // Deposit grid cells = the legend tile followed by every aggregate, as one
  // flat list so VirtuosoGrid keeps the legend as the first grid cell (a Header
  // would sit outside the grid and break column alignment).
  const depositCells = useMemo<
    ({ kind: "example" } | { kind: "agg"; agg: AggregateTile })[]
  >(
    () => [{ kind: "example" }, ...filteredAggregate.map((agg) => ({ kind: "agg" as const, agg }))],
    [filteredAggregate],
  );

  return (
    <div className="layout">
      {/* Left column: the pool with the blog underneath. */}
      <div className="layout-left">
        <div className="pool-stack">
        <nav className="bookmarks" aria-label="Storage">
          <button
            type="button"
            className={"bookmark" + (view === "pool" ? " active" : "")}
            onClick={() => switchPool(lastPoolKind, false)}
          >
            The Pool
          </button>
          <button
            type="button"
            className={"bookmark" + (view === "vault" ? " active" : "")}
            onClick={() => switchPool("myvault")}
          >
            My Vault <span className="bookmark-tag">beta</span>
          </button>
          {features.includes("wishlist") && (
            <button
              type="button"
              className={"bookmark" + (view === "wishlist" ? " active" : "")}
              onClick={() => switchPool("wishlist")}
            >
              My Wishlist
            </button>
          )}
          <button
            type="button"
            className={"bookmark" + (view === "trades" ? " active" : "")}
            onClick={() => switchPool(lastPoolKind, true)}
          >
            Trades <span className="bookmark-tag">beta</span>
          </button>
        </nav>
        <section className="panel pool-panel bookmarked">
        <div className="pool-head">
          <h2>{pool === "myvault" ? "My Vault" : pool === "wishlist" ? "My Wishlist" : tradeMode ? "Trades" : "The Pool"}</h2>
          <span className="pool-count">
            {pool === "wishlist"
                ? ""
                : pool === "myvault"
                ? ctxHalf
                  ? `${ctxHalf.used} / ${ctxHalf.slots} slots`
                  : sessionIgn
                    ? "…"
                    : ""
                : loading
                  ? "…"
                  : `${poolInstances.length} item${poolInstances.length === 1 ? "" : "s"}`}
          </span>
        </div>
        {(view === "pool" || view === "trades") && (
          <div className="pool-tabs">
            <button
              className={"nav-link" + (pool === "seasonal" ? " active" : "")}
              onClick={() => switchPool("seasonal", tradeMode)}
            >
              Seasonal
            </button>
            <button
              className={"nav-link" + (pool === "nonseasonal" ? " active" : "")}
              onClick={() => switchPool("nonseasonal", tradeMode)}
            >
              Non-seasonal
            </button>
          </div>
        )}
        {pool === "myvault" && (
          <div className="pool-tabs">
            <button
              className={"nav-link" + (vaultHalf === "seasonal" ? " active" : "")}
              onClick={() => switchVaultHalf("seasonal")}
            >
              Seasonal{vault ? ` · ${vault.seasonal.used}/${vault.seasonal.slots}` : ""}
            </button>
            <button
              className={"nav-link" + (vaultHalf === "nonseasonal" ? " active" : "")}
              onClick={() => switchVaultHalf("nonseasonal")}
            >
              Non-seasonal{vault ? ` · ${vault.nonseasonal.used}/${vault.nonseasonal.slots}` : ""}
            </button>
          </div>
        )}
        {pool === "myvault" && (
          <div className="vault-head">
            {!sessionIgn ? (
              <p className="hint">Log in to see your vault. Every account gets its own slots, split between a seasonal and a non-seasonal vault, each on a bot of its own.</p>
            ) : vault && ctxHalf ? (
              <>
                <div className="vault-alloc">
                  <span className="vault-alloc-label">{ctxSeasonal ? "Seasonal" : "Non-seasonal"} slots</span>
                  <button
                    type="button"
                    className="login-char-btn"
                    disabled={vaultAllocBusy || ctxHalf.slots < vault.block || ctxHalf.used + ctxHalf.wishes > ctxHalf.slots - vault.block}
                    onClick={() => allocateVault(ctxSeasonal, ctxHalf.slots - vault.block)}
                    title={`Take ${vault.block} slots away from this vault`}
                  >
                    −{vault.block}
                  </button>
                  <span className="vault-alloc-count">{ctxHalf.slots}</span>
                  <button
                    type="button"
                    className="login-char-btn"
                    disabled={vaultAllocBusy || vault.unallocated < vault.block}
                    onClick={() => allocateVault(ctxSeasonal, ctxHalf.slots + vault.block)}
                    title={`Give this vault ${vault.block} more slots`}
                  >
                    +{vault.block}
                  </button>
                  <span className="pool-option-hint">
                    {vault.unallocated > 0
                      ? `${vault.unallocated} of your ${vault.total} slots unallocated`
                      : `all ${vault.total} of your slots are allocated — free ${vault.block} from the ${ctxSeasonal ? "non-seasonal" : "seasonal"} vault to move them here`}
                  </span>
                  {ctxHalf.slots > 0 && ctxHalf.used + ctxHalf.wishes > ctxHalf.slots - vault.block && (
                    <span className="pool-option-hint">
                      · {ctxHalf.used} item{ctxHalf.used === 1 ? "" : "s"}{ctxHalf.wishes > 0 ? ` and ${ctxHalf.wishes} wish${ctxHalf.wishes === 1 ? "" : "es"}` : ""} keep these slots busy
                    </span>
                  )}
                </div>
                <div className="vault-bot">
                  {ctxHalf.slots === 0 ? (
                    `No slots here yet — press +${vault.block} to open your ${ctxSeasonal ? "seasonal" : "non-seasonal"} vault.`
                  ) : ctxHalf.bot ? (
                    <>
                      Your {ctxSeasonal ? "seasonal" : "non-seasonal"} bot: <strong>{ctxHalf.bot.ign || "(logging in for the first time)"}</strong>
                      {ctxHalf.bot.online ? ` · online on ${ctxHalf.bot.server}` : " · offline until you trade"}
                    </>
                  ) : (
                    "No bot assigned yet — one is set aside the first time you store something here."
                  )}
                  {vault.items.some((i) => i.seasonal === ctxSeasonal && i.inTransit) && (
                    <span className="pool-option-hint">
                      {" "}· {vault.items.filter((i) => i.seasonal === ctxSeasonal && i.inTransit).length} item(s) still being moved to your bot
                    </span>
                  )}
                  {vault.items.some((i) => i.seasonal === ctxSeasonal && i.lost) && (
                    <span className="pool-option-hint" style={{ color: "var(--bad)" }}>
                      {" "}· {vault.items.filter((i) => i.seasonal === ctxSeasonal && i.lost).length} item(s) on a bot the fleet no longer reaches
                    </span>
                  )}
                </div>
                {vaultErr && <p className="login-err">{vaultErr}</p>}
              </>
            ) : (
              <p className="hint">{vaultErr ?? "Loading your vault…"}</p>
            )}
          </div>
        )}
        {pool === "wishlist" ? (
          <WishlistPanel ign={sessionIgn} catalog={catalog} refreshKey={poolKey + feedKey + vaultKey} />
        ) : (
        <>
        <div className="pool-controls">
          <TagSearch
            tags={tags}
            onTagsChange={setTags}
            text={query}
            onTextChange={setQuery}
            suggestions={suggestions}
            placeholder="Search items, enchantments or effects…"
          />
          <label className="pool-sort">
            <span>Sort</span>
            <select value={sort} onChange={(e) => setSort(e.target.value as SortKey)}>
              {(Object.keys(SORT_LABELS) as (keyof typeof SORT_LABELS)[])
                // Rarity only means something per-instance (withdraw grid).
                .filter((k) => k !== "rarity" || tab !== "deposit")
                .map((k) => (
                  <option key={k} value={k}>
                    {SORT_LABELS[k]}
                  </option>
                ))}
              <optgroup label="Stats">
                {STAT_SORTS.map((k) => (
                  <option key={k} value={`stat:${k}`}>
                    {STAT_SORT_LABELS[k]}
                  </option>
                ))}
              </optgroup>
            </select>
          </label>
        </div>
        <div className="mat-filters">
          <MaterialSliders value={matFilter} exact={matExact} onToggleExact={toggleMatExact} onChange={onMatChange} />
          <div className="side-sliders">
            <FeedSlider value={feedMin} steps={feedSteps} exact={feedExact} onToggleExact={toggleFeedExact} onChange={setFeedMin} />
            <EnchantSlider value={enchMin} exact={enchExact} onToggleExact={toggleEnchExact} onChange={setEnchMin} />
          </div>
        </div>
        <div className="pool-options">
          <label className="pool-option">
            <input
              type="checkbox"
              checked={stackByType}
              onChange={(e) => setStackByType(e.target.checked)}
            />
            <span>Collapse by rarity</span>
            <span className="pool-option-hint">one tile per item and rarity, enchants ignored</span>
          </label>
        </div>
        <div className="pool-body">
        <FilterRail
          selectedClass={classFilter}
          onSelectClass={selectClass}
          selectedSlot={slotFilter}
          onSelectSlot={selectSlot}
          selectedConsumable={consumableFilter}
          onSelectConsumable={selectConsumable}
        />
        <div className="pool-grid-col">
        <div className="pool-grid-wrap" ref={setScrollParent}>
          {loading ? (
            <p style={{ color: "var(--muted)" }}>Loading…</p>
          ) : poolErr ? (
            <p style={{ color: "var(--bad)" }}>
              Bot service unreachable — couldn&rsquo;t fetch the pool.{" "}
              <span style={{ color: "var(--muted)" }}>({poolErr})</span>
            </p>
          ) : tab === "deposit" ? (
            // Deposit grid renders every catalog item, even ones at ×0,
            // so a player can see what the pool accepts regardless of
            // current stock. Empty-search-result still gets its own
            // message, but "pool is empty" doesn't apply here.
            filteredAggregate.length === 0 ? (
              <p style={{ color: "var(--muted)" }}>No items match your search.</p>
            ) : (
              <VirtuosoGrid
                data={depositCells}
                customScrollParent={scrollParent ?? undefined}
                listClassName="pool-grid"
                itemClassName="pool-cell"
                computeItemKey={(_i, cell) =>
                  cell.kind === "example" ? "example" : cell.agg.itemId
                }
                itemContent={(_i, cell) =>
                  cell.kind === "example" ? (
                    <ExampleTile />
                  ) : (
                    <AggregateTile agg={cell.agg} />
                  )
                }
              />
            )
          ) : filtered.length === 0 ? (
            <p style={{ color: "var(--muted)" }}>
              {poolInstances.length === 0
                ? pool === "myvault"
                  ? sessionIgn
                    ? `Your ${vaultHalf === "seasonal" ? "seasonal" : "non-seasonal"} vault is empty. Claim items from the ${vaultHalf === "seasonal" ? "seasonal" : "non-seasonal"} pool with the Claim tab, or deposit straight into it.`
                    : "Log in to see your vault."
                  : `The ${pool === "seasonal" ? "seasonal" : "non-seasonal"} pool is empty. Deposit something.`
                : "No items match your search."}
            </p>
          ) : (
            <VirtuosoGrid
              data={stacks}
              customScrollParent={scrollParent ?? undefined}
              listClassName="pool-grid"
              itemClassName="pool-cell"
              computeItemKey={(_i, s) => s.key}
              itemContent={(_i, s) => {
                const selected = s.instances.filter((i) =>
                  tray.includes(i.instanceId),
                ).length;
                return (
                  <StackTile
                    stack={s}
                    selected={selected}
                    trayFull={tray.length >= maxTray}
                    onAdd={() => addFromStack(s.instances)}
                    onHover={(rect) => setHover({ stack: s, rect })}
                    onLeave={() =>
                      setHover((cur) => (cur && cur.stack.key === s.key ? null : cur))
                    }
                  />
                );
              }}
            />
          )}
        </div>
        </div>
        </div>
        </>
        )}
      </section>
        </div>
      </div>

      <aside style={{ display: "flex", flexDirection: "column", gap: 24 }}>
        <div className="panel">
          <h2>
            {sessionIgn ? (
              <a className="profile-name-link" href={`/u/${encodeURIComponent(sessionIgn)}`}>
                <PlayerName ign={sessionIgn} />
              </a>
            ) : (
              "Login"
            )}
          </h2>
          <LoginPanel ign={sessionIgn} onChange={onSessionChange} />
        </div>
        {/* Server-backed: whatever this character has queued or mid-trade,
            with a cancel per request, surviving reloads and tab switches. */}
        <OpenRequests ign={sessionIgn} refreshKey={feedKey + poolKey} onChanged={reload} />
        {pool === "wishlist" ? (
          <div className="panel">
            <h2>How it works</h2>
            <ul className="wish-help">
              <li>Pick an item and how many enchantment slots it should have. Each slot gets its own filter — by name, or by what the enchantment does.</li>
              <li>A row describes one enchantment; add an &ldquo;or&rdquo; row for alternatives. Leave a slot empty to accept any enchantment there.</li>
              <li>A wish is for the seasonal or the non-seasonal pool. A match that reaches that pool is claimed into your vault for it, priced like a claim, and the wish is spent. Items and wishes together can&apos;t exceed that vault&apos;s slots.</li>
              <li>A wish is checked the moment you make it and on every pool change after. Older wishes are served first, across all players.</li>
            </ul>
          </div>
        ) : tradeMode ? (
          <div className="panel">
            <h2>Offer</h2>
            <TradePanel tray={trayInstances} onRemove={removeFromTrayAt} onClear={clearTray} seasonal={ctxSeasonal} onPosted={reload} maxTray={MAX_TRADE_TRAY} />
          </div>
        ) : (
          <div className="panel">
            <h2>Transact</h2>
            <TxForm
              ign={sessionIgn}
              tab={tab}
              onTabChange={setTab}
              mode={pool === "myvault" ? "vault" : "pool"}
              seasonal={ctxSeasonal}
              vault={ctxHalf}
              onVaultChanged={bumpVault}
              trayInstances={trayInstances}
              onRemoveFromTray={removeFromTrayAt}
              onClearTray={clearTray}
              onComplete={reload}
              maxTray={MAX_TRAY}
            />
          </div>
        )}
        <div className="panel">
            <h2> Recent Activity</h2>
            <RecentActivity refreshKey={feedKey} />
        </div>
      </aside>
      {hover && <TilePortalTip hover={hover} enchSprites={enchSprites} />}
    </div>
  );
}

function TilePortalTip({
  hover,
  enchSprites,
}: {
  hover: { stack: Stack; rect: DOMRect };
  enchSprites: Map<number, string>;
}) {
  if (typeof document === "undefined") return null;
  const { stack, rect } = hover;
  const inst = stack.rep;
  // Anchor the tooltip just above the tile, centered horizontally. Done
  // via inline style because the position depends on viewport coords at
  // hover time — CSS can't express it.
  // Above the tile when there is room for the stat block, else below it.
  const above = rect.top > Math.min(420, window.innerHeight * 0.55);
  const style: React.CSSProperties = {
    position: "fixed",
    left: rect.left + rect.width / 2,
    top: above ? rect.top - 6 : rect.bottom + 6,
    transform: above ? "translate(-50%, -100%)" : "translate(-50%, 0)",
    zIndex: 1000,
    pointerEvents: "none",
  };
  return createPortal(
    <div className="pool-tile-tip pool-tile-tip-floating" style={style}>
      <div className="pool-tile-tip-name">{inst.itemName}</div>
      <div className={"pool-tile-tip-rarity rarity-" + inst.rarity}>{inst.rarity}</div>
      <ItemStats itemName={inst.itemName} enchantIds={stack.mixed ? [] : inst.enchantments.map((e) => e.id)} />
      <DismantleLine itemName={inst.itemName} />
      <FeedLine itemName={inst.itemName} />
      {stack.mixed && (
        <div className="pool-tile-tip-bot">mixed enchantments — stacked by rarity &amp; type</div>
      )}
      {!stack.mixed && inst.enchantments.length > 0 && (
        <ul className="pool-tile-tip-enchants">
          {inst.enchantments.map((e, i) => {
            const sprite = enchSprites.get(e.id);
            return (
              <li key={i}>
                {sprite && (
                  <img
                    className="pool-tile-tip-enchant-icon"
                    src={`data:image/png;base64,${sprite}`}
                    alt=""
                    aria-hidden="true"
                  />
                )}
                <span>{e.name ?? `Enchant #${e.id}`}</span>
              </li>
            );
          })}
        </ul>
      )}
      {stack.instances.length > 1 && (
        <div className="pool-tile-tip-bot">×{stack.instances.length} in pool</div>
      )}
      {stack.botIgns.length > 0 && (
        <div className="pool-tile-tip-bot">
          held by {stack.botIgns.slice(0, 4).join(", ")}
          {stack.botIgns.length > 4 ? ", …" : ""}
        </div>
      )}
    </div>,
    document.body,
  );
}

// Three snapping sliders (common/rare/mythical) that filter the pool to items
// yielding ≥ the selected amount of each material. Each slider is index-based
// over its material's existing amounts, so it snaps to real values only.
const MAT_SLIDER_ROWS = [
  { key: "common", label: "Common", icon: "/forge/common.png" },
  { key: "rare", label: "Rare", icon: "/forge/rare.png" },
  { key: "legendary", label: "Legendary", icon: "/forge/legendary.png" },
  { key: "mythical", label: "Mythical", icon: "/forge/mythical.png" },
] as const;

const MaterialSliders = memo(function MaterialSliders({
  value,
  exact,
  onToggleExact,
  onChange,
}: {
  value: MatFilter;
  exact: boolean;
  onToggleExact: () => void;
  onChange: (key: MatKey, amount: number) => void;
}) {
  return (
    <div className="mat-sliders" role="group" aria-label="Filter by dismantle value">
      {MAT_SLIDER_ROWS.map(({ key, label, icon }) => {
        const steps = MAT_STEPS[key];
        const amount = value[key];
        const idx = Math.max(0, steps.indexOf(amount));
        return (
          <label className="mat-slider" key={key}>
            <img className="mat-slider-icon" src={icon} alt="" aria-hidden="true" />
            <span className="mat-slider-label">{label}</span>
            <input
              type="range"
              min={0}
              max={steps.length - 1}
              step={1}
              value={idx}
              aria-label={`Minimum ${label} material`}
              aria-valuetext={exact ? `exactly ${amount}` : amount === 0 ? "any" : `at least ${amount}`}
              onChange={(e) => onChange(key, steps[Number(e.target.value)])}
            />
            <SliderValue className="mat-slider-val" amount={amount} exact={exact} onToggle={onToggleExact} />
          </label>
        );
      })}
    </div>
  );
});

// Feed-power slider (right of the forge sliders). Index-based over existing feed
// values so it snaps to real amounts; filters to items feeding ≥ the amount.
// Feed-power slider row (index-based over the given depositable steps) and the
// enchant-slots slider row live together in the right-side panel.
const MAX_ENCH_SLOTS = 2;

const FeedSlider = memo(function FeedSlider({
  value,
  steps,
  exact,
  onToggleExact,
  onChange,
}: {
  value: number;
  steps: number[];
  exact: boolean;
  onToggleExact: () => void;
  onChange: (amount: number) => void;
}) {
  const idx = Math.max(0, steps.indexOf(value));
  return (
    <div className="side-slider">
      <span className="side-slider-label">Feed Power</span>
      <input
        type="range"
        min={0}
        max={Math.max(1, steps.length - 1)}
        step={1}
        value={idx}
        aria-label="Minimum feed power"
        aria-valuetext={exact ? `exactly ${value}` : value === 0 ? "any" : `at least ${value}`}
        onChange={(e) => onChange(steps[Number(e.target.value)] ?? 0)}
      />
      <SliderValue className="side-slider-val" amount={value} exact={exact} onToggle={onToggleExact} />
    </div>
  );
});

const EnchantSlider = memo(function EnchantSlider({
  value,
  exact,
  onToggleExact,
  onChange,
}: {
  value: number;
  exact: boolean;
  onToggleExact: () => void;
  onChange: (amount: number) => void;
}) {
  return (
    <div className="side-slider">
      <span className="side-slider-label">Enchant Slots</span>
      <input
        type="range"
        min={0}
        max={MAX_ENCH_SLOTS}
        step={1}
        value={value}
        aria-label="Minimum enchant slots"
        aria-valuetext={exact ? `exactly ${value}` : value === 0 ? "any" : `at least ${value}`}
        onChange={(e) => onChange(Number(e.target.value))}
      />
      <SliderValue className="side-slider-val" amount={value} exact={exact} onToggle={onToggleExact} />
    </div>
  );
});

// Forge dismantle value inside the tooltip: one material icon + count per tier
// the item yields. Renders nothing for items with no dismantle value (non-UT/ST
// gear, or UT/ST RealmEye lists no value for).
// In-game style stat block for the hover card: what the item is, who can use
// it, what it does. Everything comes from item-tooltips.json; items without an
// entry (eggs, retired items) render nothing here.
function ItemStats({ itemName, enchantIds = [] }: { itemName: string; enchantIds?: number[] }) {
  const t = ITEM_TOOLTIPS[normName(itemName)];
  if (!t) return null;
  const classes = t.c.length === 0 ? null : t.c[0] === "ALL" ? "All classes" : t.c.join(", ");
  const signed = (v: number) => (v >= 0 ? `+${round1(v)}` : `${round1(v)}`);
  const ench = applyEnchants(t, enchantIds);
  const boosted = (changed: boolean) => "tip-val" + (changed ? " tip-boost" : "");
  // On-equip row: the item's own stats plus every flat enchant bonus, in the
  // item's order first, then stats only the enchants add.
  const equipRows: { s: string; v: number; changed: boolean; r?: string; pct?: boolean }[] = [];
  for (const e of t.e ?? []) {
    if (e.r || e.pct) { equipRows.push({ ...e, changed: false }); continue; }
    const st = ench.stats.get(e.s)!;
    equipRows.push({ s: e.s, v: st.base + st.bonus, changed: st.bonus !== 0 });
  }
  for (const [s, st] of ench.stats) if (!(t.e ?? []).some((e) => e.s === s && !e.r && !e.pct)) equipRows.push({ s, v: st.bonus, changed: true });
  const xp = (t.xp ?? 0) + ench.xp;
  return (
    <div className="tip-stats">
      <div className="tip-kind">
        {t.t && <span className="tip-tier">{t.t}</span>}
        <span>{t.k}</span>
        {classes && <span className="tip-classes">{classes}</span>}
      </div>
      {t.d && <div className="tip-desc">{t.d}</div>}
      {t.a?.map((a, i) => {
        const lo = Math.round(a.dmg[0] * ench.dmg[0]), hi = Math.round(a.dmg[1] * ench.dmg[1]);
        const rof = Math.round(a.rof * ench.rof), range = round1(a.range * ench.rng);
        return (
        <div className="tip-attack" key={i}>
          <div className="tip-row">
            <span className="tip-label">{i === 0 ? "Damage" : "Alt damage"}</span>
            <span className={boosted(lo !== a.dmg[0] || hi !== a.dmg[1])}>
              {lo === hi ? lo : `${lo}–${hi}`}
              {lo !== hi && <span className="tip-dim"> (avg {(lo + hi) / 2})</span>}
            </span>
          </div>
          {a.shots > 1 && (
            <div className="tip-row">
              <span className="tip-label">Shots</span>
              <span className="tip-val">{a.shots}{a.arc ? <span className="tip-dim"> ({a.arc}° apart)</span> : null}</span>
            </div>
          )}
          {a.burst && (
            <div className="tip-row"><span className="tip-label">Burst</span><span className="tip-val">{a.burst}</span></div>
          )}
          <div className="tip-row"><span className="tip-label">Range</span><span className={boosted(range !== a.range)}>{range}</span></div>
          {rof !== 100 && (
            <div className="tip-row"><span className="tip-label">Rate of Fire</span><span className={boosted(rof !== a.rof)}>{rof}%</span></div>
          )}
        </div>
        );
      })}
      {t.p?.map((line) => <div className="tip-line" key={line}>{line}</div>)}
      {equipRows.length > 0 && (
        <div className="tip-row">
          <span className="tip-label">On Equip</span>
          <span className="tip-val tip-equip">
            {equipRows.map((e, i) => (
              <span key={i} className={e.changed ? "tip-boost" : undefined}>{e.pct ? `${signed(e.v)}% ${e.s}` : `${signed(e.v)} ${e.s}`}{e.r ? <span className="tip-dim"> (of {e.r})</span> : null}</span>
            ))}
          </span>
        </div>
      )}
      {t.mp !== undefined && (
        <div className="tip-row"><span className="tip-label">MP Cost</span><span className={boosted(ench.mp !== 1)}>{Math.round(t.mp * ench.mp)}</span></div>
      )}
      {(t.mpe !== undefined || t.mps !== undefined) && (
        <div className="tip-row">
          <span className="tip-label">MP Cost</span>
          <span className="tip-val">{[t.mps !== undefined ? `${t.mps}/s` : null, t.mpe !== undefined ? `${t.mpe} on release` : null].filter(Boolean).join(", ")}</span>
        </div>
      )}
      {t.cd !== undefined && (
        <div className="tip-row"><span className="tip-label">Cooldown</span><span className="tip-val">{t.cd}s</span></div>
      )}
      {t.l?.map((line) => <div className="tip-line" key={line}>{line}</div>)}
      {t.x?.map((x, i) => (
        <div className="tip-line" key={i}>
          {x.n && <span className="tip-x-name">{x.n}: </span>}
          {x.d}
        </div>
      ))}
      {ench.lines.map((line, i) => <div className="tip-line tip-boost" key={`e${i}`}>{line}</div>)}
      {t.set && <div className="tip-line tip-dim">Set: {t.set}</div>}
      {(t.xp !== undefined || ench.xp > 0) && (
        <div className="tip-row"><span className="tip-label">XP Bonus</span><span className={boosted(ench.xp > 0)}>{round1(xp)}%</span></div>
      )}
    </div>
  );
}

function DismantleLine({ itemName }: { itemName: string }) {
  const dv = itemDismantle(itemName);
  if (!dv) return null;
  const tiers = FORGE_TIERS.filter((t) => dv[t.key] != null);
  if (tiers.length === 0) return null;
  return (
    <div className="pool-tile-tip-dismantle">
      <span className="pool-tile-tip-dismantle-label">Dismantle</span>
      {tiers.map((t) => (
        <span key={t.key} className="pool-tile-tip-dismantle-mat">
          {dv[t.key]}
          <img src={t.icon} alt={t.label} title={t.label} aria-hidden="true" />
        </span>
      ))}
    </div>
  );
}

// Pet feed power inside the tooltip. Renders nothing for items with no feed value.
function FeedLine({ itemName }: { itemName: string }) {
  const fp = itemFeedPower(itemName);
  if (fp <= 0) return null;
  return (
    <div className="pool-tile-tip-feed">
      <span className="pool-tile-tip-feed-label">Feed Power</span>
      <span className="pool-tile-tip-feed-val">{fp}</span>
    </div>
  );
}

// Rarity corner badge. uncommon/rare have real RotMG-style PNG icons in
// /public; legendary/divine fall back to the colored dot until we have
// matching art for those tiers.
const RARITY_ICON: Partial<Record<Rarity, string>> = {
  uncommon: "/uncommon.png",
  rare: "/rare.png",
};

function RarityBadge({ rarity }: { rarity: Rarity }) {
  const icon = RARITY_ICON[rarity];
  if (icon) {
    // Rare's source asset is wider than uncommon (it spans two enchant
    // slots visually), so we render it at double width and keep height
    // square. The .rarity-icon CSS positions it the same way regardless.
    const wide = rarity === "rare";
    return (
      <img
        className={"rarity-icon" + (wide ? " rarity-icon-wide" : "")}
        src={icon}
        alt=""
        aria-hidden="true"
      />
    );
  }
  return (
    <span
      className="rarity-dot"
      style={{ background: RARITY_COLOR[rarity] }}
      aria-hidden="true"
    />
  );
}

// One tile per stack of identical instances (withdraw grid only — the
// deposit grid uses AggregateTile). Shows how many copies exist and how
// many are already in the tray; each click reserves one more.
const StackTile = memo(function StackTile({
  stack,
  selected,
  trayFull,
  onAdd,
  onHover,
  onLeave,
}: {
  stack: Stack;
  selected: number;
  trayFull: boolean;
  onAdd: () => void;
  onHover: (rect: DOMRect) => void;
  onLeave: () => void;
}) {
  const inst = stack.rep;
  const total = stack.instances.length;
  const exhausted = selected >= total;
  const clickable = !exhausted && !trayFull;

  return (
    <button
      type="button"
      className={
        "pool-tile rarity-" +
        inst.rarity +
        (clickable ? " clickable" : "") +
        (exhausted && selected > 0 ? " in-tray" : "") +
        (!clickable && selected === 0 ? " unclickable" : "")
      }
      onClick={clickable ? onAdd : undefined}
      onMouseEnter={(e) => onHover(e.currentTarget.getBoundingClientRect())}
      onMouseLeave={onLeave}
      onFocus={(e) => onHover(e.currentTarget.getBoundingClientRect())}
      onBlur={onLeave}
      disabled={!clickable && selected === 0}
      aria-label={`${inst.itemName} ×${total}`}
    >
      <ItemSprite name={inst.itemName} />
      {inst.rarity !== "common" && <RarityBadge rarity={inst.rarity} />}
      {(total > 1 || selected > 0) && (
        <span className="aggregate-count">
          {selected > 0 ? `${selected}/${total}` : `×${total}`}
        </span>
      )}
    </button>
  );
});

// Corner badges shrink as their text grows so a long value ("quantity",
// Corner badge that SCALES to fit its tile via transform, re-measured on
// tile resize. font-size shrinking wasn't enough: Chrome enforces a
// user-configurable minimum font size, so tiny px values silently render
// bigger and overflow anyway — transform: scale() is immune to that floor.
function FitBadge({
  className,
  corner,
  children,
}: {
  className: string;
  corner: "tl" | "br";
  children: React.ReactNode;
}) {
  const ref = useRef<HTMLSpanElement>(null);
  useEffect(() => {
    const el = ref.current;
    const tile = el?.parentElement;
    if (!el || !tile) return;
    const fit = () => {
      // Reset first so scrollWidth reflects the FULL unscaled text width
      // (belt-and-braces; scrollWidth already ignores transform). avail/w
      // is exactly the shrink needed; 8px ≈ the badge's corner insets.
      el.style.transform = "";
      const avail = tile.clientWidth - 8;
      const w = el.scrollWidth;
      if (w > avail && w > 0) el.style.transform = `scale(${avail / w})`;
    };
    // Defer the first measure a frame so the responsive grid has settled
    // its final column width — measuring during mount catches a stale
    // width and (with ResizeObserver unreliable in some webviews) never
    // corrects. A window-resize listener covers the only thing that
    // actually changes tile width after that: the viewport.
    const raf = requestAnimationFrame(fit);
    window.addEventListener("resize", fit);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", fit);
    };
  }, [children]);
  return (
    <span
      ref={ref}
      className={className}
      style={{ transformOrigin: corner === "tl" ? "top left" : "bottom right" }}
    >
      {children}
    </span>
  );
}

// Legend tile pinned to the deposit grid's first slot: labels the badge
// positions instead of showing an item, so the number in each corner of
// the real tiles explains itself.
function ExampleTile() {
  return (
    <div
      className="pool-tile aggregate-tile example-tile"
      title={"How to read these tiles: top-left is the leaderboard points one deposit earns (enchanted copies earn more), bottom-right is how many are in the pool."}
      aria-label="Legend: top-left shows points earned per deposit, bottom-right shows quantity in pool"
    >
      <FitBadge className="points-badge" corner="tl">points</FitBadge>
      <span className="example-tile-label">Example</span>
      <FitBadge className="aggregate-count" corner="br">quantity</FitBadge>
    </div>
  );
}

// Aggregate tile used in deposit mode. Same visual frame as PoolTile but
// shows a quantity badge instead of per-instance rarity (the bag of items
// may span multiple rarities/enchant sets — we don't render a single
// rarity color in that case, just the count). Non-interactive: deposit
// flow doesn't care which specific items go in.
const AggregateTile = memo(function AggregateTile({
  agg,
}: {
  agg: {
    itemId: string;
    itemName: string;
    sprite: string | null;
    rarity: Rarity;
    count: number;
    points: number;
    bots: string[];
  };
}) {
  // Title attribute is the simplest hover affordance — the per-instance
  // PoolTile uses a portaled rich tooltip for enchant icons, but in deposit
  // mode we're not surfacing enchants (the whole point is "any tier").
  const empty = agg.count === 0;
  const title =
    (empty
      ? `${agg.itemName} ×0 (accepted, but pool is out)`
      : `${agg.itemName} ×${agg.count}` +
        (agg.bots.length > 0 ? `\nheld by ${agg.bots.join(", ")}` : "")) +
    `\nworth ${agg.points} pt${agg.points === 1 ? "" : "s"} deposited (enchanted copies earn more)`;
  return (
    <div
      className={
        "pool-tile rarity-" + agg.rarity + " aggregate-tile" + (empty ? " aggregate-empty" : "")
      }
      title={title}
      aria-label={`${agg.itemName} ×${agg.count}, worth ${agg.points} point${agg.points === 1 ? "" : "s"}`}
    >
      <FitBadge className="points-badge" corner="tl">{agg.points}</FitBadge>
      <ItemSprite name={agg.itemName} />
      <FitBadge className="aggregate-count" corner="br">×{agg.count}</FitBadge>
    </div>
  );
});
