// Regenerates src/server/routes.ts from src/server/api/**/route.ts.
// Run after adding or removing a route file:  node scripts/gen-routes.mjs
import fs from "node:fs";
import path from "node:path";

const root = "src/server/api";
const files = [];
(function walk(d) {
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name === "route.ts") files.push(p);
  }
})(root);
files.sort();

const imports = [];
const regs = [];
files.forEach((f, i) => {
  const rel = path.relative(root, path.dirname(f)).split(path.sep);
  const url = "/api/" + rel.map((s) => s.replace(/^\[(.+)\]$/, ":$1")).join("/");
  const src = fs.readFileSync(f, "utf8");
  const methods = [...src.matchAll(/^export (?:async )?function (GET|POST|PUT|PATCH|DELETE)\b/gm)].map((m) => m[1]);
  const mod = "r" + i;
  imports.push(`import * as ${mod} from "@/server/api/${rel.join("/")}/route";`);
  for (const m of methods) regs.push(`  app.${m.toLowerCase()}("${url}", h(${mod}.${m}));`);
});

const out = `// GENERATED by scripts/gen-routes.mjs — do not edit by hand.
// Maps every src/server/api/**/route.ts to its URL, mirroring the old Next
// file-based routing so route bodies could move over unchanged.
import type { Hono } from "hono";
import { h } from "@/server/http";
${imports.join("\n")}

export function registerRoutes(app: Hono): void {
${regs.join("\n")}
}
`;
fs.writeFileSync("src/server/routes.ts", out);
console.log(`routes: ${regs.length} handlers across ${files.length} files`);
