// Stat ids carried in ObjectStatusData. Only the ones the bots read are
// named individually; the rest still parse (the wire format doesn't care).
export const Stat = {
  MAXHP: 0, HP: 1, SIZE: 2, MAXMP: 3, MP: 4, NEXTLEVELEXP: 5, EXP: 6, LEVEL: 7,
  INVENTORY0: 8, INVENTORY11: 19,
  ATTACK: 20, DEFENSE: 21, SPEED: 22,
  // 23 and 24 came on the wire 2026-09-22 (USSouth3 Nexus) as compressed ints (1 and 0) with the
  // usual -1 secondary, the stream staying aligned through ATTACK right after; the game names them nowhere readable.
  UNKNOWN23: 23, UNKNOWN24: 24,
  TEXTURE: 25, VITALITY: 26, WISDOM: 27, DEXTERITY: 28,
  CONDITION: 29, NUMSTARS: 30, NAME: 31, TEX1: 32, TEX2: 33, MERCHANDISETYPE: 34, CREDITS: 35,
  MERCHANDISEPRICE: 36, ACTIVE: 37, ACCOUNTID: 38, FAME: 39, MERCHANDISECURRENCY: 40, CONNECT: 41,
  MERCHANDISECOUNT: 42, MERCHANDISEMINSLEFT: 43, MERCHANDISEDISCOUNT: 44, MERCHANDISERANKREQ: 45,
  MAXHPBOOST: 46, MAXMPBOOST: 47, ATTACKBOOST: 48, DEFENSEBOOST: 49, SPEEDBOOST: 50,
  VITALITYBOOST: 51, WISDOMBOOST: 52, DEXTERITYBOOST: 53, OWNERACCOUNTID: 54, RANKREQUIRED: 55,
  NAMECHOSEN: 56, CURRFAME: 57, NEXTCLASSQUESTFAME: 58, LEGENDARYRANK: 59, SINKLEVEL: 60,
  ALTTEXTURE: 61, GUILDNAME: 62, GUILDRANK: 63, BREATH: 64, XPBOOSTED: 65, XPTIMER: 66,
  LDTIMER: 67, LTTIMER: 68, HEALTHPOTIONSTACK: 69, MAGICPOTIONSTACK: 70, MATERIALAMOUNT: 71,
  MATERIALCAP: 72, SUMMONHP: 73, SUMMONMANA: 74, SUMMONATT: 75,
  // 78 arrived on the wire 2026-09-04 as a length-prefixed string ("Name|Name",
  // seen on a player standing in the USSouth Nexus). Reading it as an int
  // desynced every UPDATE that carried it, so no bot on that server ever
  // reached in-world.
  UNKNOWN78: 78, HASBACKPACK: 79, ENCHANTMENTS: 80,
  PETINSTANCEID: 81, PETNAME: 82, PETTYPE: 83, PETRARITY: 84, PETMAXABILITYPOWER: 85, PETFAMILY: 86,
  PETFIRSTABILITYPOINT: 87, PETSECONDABILITYPOINT: 88, PETTHIRDABILITYPOINT: 89,
  PETFIRSTABILITYPOWER: 90, PETSECONDABILITYPOWER: 91, PETTHIRDABILITYPOWER: 92,
  PETFIRSTABILITYTYPE: 93, PETSECONDABILITYTYPE: 94, PETTHIRDABILITYTYPE: 95, NEWCON: 96,
  FORTUNETOKEN: 97, SUPPORTERPOINTS: 98, SUPPORTER: 99, CHALLENGERSTARBG: 100, SUMMONPOWER: 101,
  PROJECTILESPEEDMULT: 102, PROJECTILELIFEMULT: 103, OPENEDATTIMESTAMP: 104,
  EXALTEDATK: 105, EXALTEDDEFENSE: 106, EXALTEDSPD: 107, EXALTEDVIT: 108, EXALTEDWIS: 109,
  EXALTEDDEX: 110, EXALTEDHP: 111, EXALTEDMP: 112, EXALTATIONBONUSDMG: 113, PETOBJECTID: 114,
  GRAVEACCOUNTID: 115, POTIONONETYPE: 116, POTIONTWOTYPE: 117, POTIONTHREETYPE: 118, POTIONBELT: 119,
  FORGEFIRE: 120, MODIFIERS: 121, MISSIONSTATS: 122, UNKNOWN123: 123, PROJDMGMULT: 124,
  ABILITYUSEDISCOUNT: 125, SAVLOCK: 126, DUSTAMOUNT: 127, CRUCIBLE: 128, CRUCIBLECURRENT: 129,
  DAMAGERECEIVEDMULT: 130, BACKPACK0: 131, BACKPACK7: 138, BACKPACK15: 146, DUSTCAP: 147,
  ACCOUNTLEVEL: 148, ACCOUNTLEVELPROGRESS: 149, ACCOUNTLEVELTARGET: 150, SEASONLEVEL: 151,
  // 152 and 153 (2026-09-22): compressed ints (15 and 30578 on a player in the Nexus), between the
  // season level and DISCOVERABLE, which followed in step; likely more season or account-level counters.
  UNKNOWN152: 152, UNKNOWN153: 153,
  DISCOVERABLE: 154, BLOODRITUAL: 155, SEASONID: 156, COMPETITIONSCORE: 157, COMPETITIONTIER: 158,
  // 159 (2026-09-22): a compressed int (0) after the competition tier, SINKLEVEL following in step.
  UNKNOWN159: 159,
} as const;

/** Stats whose value is a string on the wire rather than a compressed int. */
export const STRING_STATS: ReadonlySet<number> = new Set([
  Stat.EXP, Stat.NAME, Stat.ACCOUNTID, Stat.OWNERACCOUNTID, Stat.GUILDNAME,
  Stat.MATERIALAMOUNT, Stat.MATERIALCAP, Stat.ENCHANTMENTS, Stat.PETNAME,
  Stat.GRAVEACCOUNTID, Stat.MODIFIERS, Stat.DUSTAMOUNT, Stat.CRUCIBLE,
  Stat.DUSTCAP, Stat.BLOODRITUAL, Stat.UNKNOWN78,
]);

export function isStringStat(statType: number): boolean {
  return STRING_STATS.has(statType);
}

const KNOWN_STATS: ReadonlySet<number> = new Set(Object.values(Stat));
/** The inventory and backpack slots are named by their endpoints only. */
const KNOWN_RANGES: readonly [number, number][] = [
  [Stat.INVENTORY0, Stat.INVENTORY11],
  [Stat.BACKPACK0, Stat.BACKPACK15],
];
export function isKnownStat(statType: number): boolean {
  return KNOWN_STATS.has(statType) || KNOWN_RANGES.some(([lo, hi]) => statType >= lo && statType <= hi);
}
